/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Type of the button
 */
export const ButtonTypeEnum = {
  Primary: "primary",
  Secondary: "secondary",
} as const;
/**
 * Type of the button
 */
export type ButtonTypeEnum = ClosedEnum<typeof ButtonTypeEnum>;

/** @internal */
export const ButtonTypeEnum$inboundSchema: z.ZodNativeEnum<
  typeof ButtonTypeEnum
> = z.nativeEnum(ButtonTypeEnum);
