/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const ChannelTypeEnum = {
  InApp: "in_app",
  Email: "email",
  Sms: "sms",
  Chat: "chat",
  Push: "push",
} as const;
export type ChannelTypeEnum = ClosedEnum<typeof ChannelTypeEnum>;

/** @internal */
export const ChannelTypeEnum$inboundSchema: z.ZodNativeEnum<
  typeof ChannelTypeEnum
> = z.nativeEnum(ChannelTypeEnum);
/** @internal */
export const ChannelTypeEnum$outboundSchema: z.ZodNativeEnum<
  typeof ChannelTypeEnum
> = ChannelTypeEnum$inboundSchema;
