/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * List of workflow IDs to associate with the subscription
 */
export type Workflows = {
  /**
   * List of workflow identifiers
   */
  ids: Array<string>;
};

export type CreateTopicSubscriptionsRequestDto = {
  /**
   * List of subscriber identifiers to subscribe to the topic (max: 100)
   */
  subscriberIds: Array<string>;
  /**
   * JSONLogic filter conditions for conditional subscription. Supports complex logical operations with AND, OR, and comparison operators. See https://jsonlogic.com/ for full typing reference.
   */
  conditions?: { [k: string]: any } | undefined;
  /**
   * List of workflow IDs to associate with the subscription
   */
  workflows?: Workflows | undefined;
};

/** @internal */
export const Workflows$inboundSchema: z.ZodType<
  Workflows,
  z.ZodTypeDef,
  unknown
> = z.object({
  ids: z.array(z.string()),
});

/** @internal */
export type Workflows$Outbound = {
  ids: Array<string>;
};

/** @internal */
export const Workflows$outboundSchema: z.ZodType<
  Workflows$Outbound,
  z.ZodTypeDef,
  Workflows
> = z.object({
  ids: z.array(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Workflows$ {
  /** @deprecated use `Workflows$inboundSchema` instead. */
  export const inboundSchema = Workflows$inboundSchema;
  /** @deprecated use `Workflows$outboundSchema` instead. */
  export const outboundSchema = Workflows$outboundSchema;
  /** @deprecated use `Workflows$Outbound` instead. */
  export type Outbound = Workflows$Outbound;
}

export function workflowsToJSON(workflows: Workflows): string {
  return JSON.stringify(Workflows$outboundSchema.parse(workflows));
}

export function workflowsFromJSON(
  jsonString: string,
): SafeParseResult<Workflows, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Workflows$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Workflows' from JSON`,
  );
}

/** @internal */
export const CreateTopicSubscriptionsRequestDto$inboundSchema: z.ZodType<
  CreateTopicSubscriptionsRequestDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  subscriberIds: z.array(z.string()),
  conditions: z.record(z.any()).optional(),
  workflows: z.lazy(() => Workflows$inboundSchema).optional(),
});

/** @internal */
export type CreateTopicSubscriptionsRequestDto$Outbound = {
  subscriberIds: Array<string>;
  conditions?: { [k: string]: any } | undefined;
  workflows?: Workflows$Outbound | undefined;
};

/** @internal */
export const CreateTopicSubscriptionsRequestDto$outboundSchema: z.ZodType<
  CreateTopicSubscriptionsRequestDto$Outbound,
  z.ZodTypeDef,
  CreateTopicSubscriptionsRequestDto
> = z.object({
  subscriberIds: z.array(z.string()),
  conditions: z.record(z.any()).optional(),
  workflows: z.lazy(() => Workflows$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateTopicSubscriptionsRequestDto$ {
  /** @deprecated use `CreateTopicSubscriptionsRequestDto$inboundSchema` instead. */
  export const inboundSchema = CreateTopicSubscriptionsRequestDto$inboundSchema;
  /** @deprecated use `CreateTopicSubscriptionsRequestDto$outboundSchema` instead. */
  export const outboundSchema =
    CreateTopicSubscriptionsRequestDto$outboundSchema;
  /** @deprecated use `CreateTopicSubscriptionsRequestDto$Outbound` instead. */
  export type Outbound = CreateTopicSubscriptionsRequestDto$Outbound;
}

export function createTopicSubscriptionsRequestDtoToJSON(
  createTopicSubscriptionsRequestDto: CreateTopicSubscriptionsRequestDto,
): string {
  return JSON.stringify(
    CreateTopicSubscriptionsRequestDto$outboundSchema.parse(
      createTopicSubscriptionsRequestDto,
    ),
  );
}

export function createTopicSubscriptionsRequestDtoFromJSON(
  jsonString: string,
): SafeParseResult<CreateTopicSubscriptionsRequestDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateTopicSubscriptionsRequestDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateTopicSubscriptionsRequestDto' from JSON`,
  );
}
