/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Source of layout creation
 */
export const Source = {
  Dashboard: "dashboard",
} as const;
/**
 * Source of layout creation
 */
export type Source = ClosedEnum<typeof Source>;

export type CreateLayoutDto = {
  /**
   * Unique identifier for the layout
   */
  layoutId: string;
  /**
   * Name of the layout
   */
  name: string;
  /**
   * Enable or disable translations for this layout
   */
  isTranslationEnabled?: boolean | undefined;
  /**
   * Source of layout creation
   */
  source?: Source | undefined;
};

/** @internal */
export const Source$outboundSchema: z.ZodNativeEnum<typeof Source> = z
  .nativeEnum(Source);

/** @internal */
export type CreateLayoutDto$Outbound = {
  layoutId: string;
  name: string;
  isTranslationEnabled: boolean;
  __source: string;
};

/** @internal */
export const CreateLayoutDto$outboundSchema: z.ZodType<
  CreateLayoutDto$Outbound,
  z.ZodTypeDef,
  CreateLayoutDto
> = z.object({
  layoutId: z.string(),
  name: z.string(),
  isTranslationEnabled: z.boolean().default(false),
  source: Source$outboundSchema.default("dashboard"),
}).transform((v) => {
  return remap$(v, {
    source: "__source",
  });
});

export function createLayoutDtoToJSON(
  createLayoutDto: CreateLayoutDto,
): string {
  return JSON.stringify(CreateLayoutDto$outboundSchema.parse(createLayoutDto));
}
