/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  GroupPreferenceFilterDto,
  GroupPreferenceFilterDto$Outbound,
  GroupPreferenceFilterDto$outboundSchema,
} from "./grouppreferencefilterdto.js";
import {
  TopicSubscriberIdentifierDto,
  TopicSubscriberIdentifierDto$Outbound,
  TopicSubscriberIdentifierDto$outboundSchema,
} from "./topicsubscriberidentifierdto.js";
import {
  WorkflowPreferenceDto,
  WorkflowPreferenceDto$Outbound,
  WorkflowPreferenceDto$outboundSchema,
} from "./workflowpreferencedto.js";

export type SubscriberIds = TopicSubscriberIdentifierDto | string;

export type Preferences =
  | WorkflowPreferenceDto
  | GroupPreferenceFilterDto
  | string;

export type CreateTopicSubscriptionsRequestDto = {
  /**
   * List of subscriber identifiers to subscribe to the topic (max: 100). Can be either a string array or an array of objects with identifier and subscriberId
   */
  subscriberIds: Array<TopicSubscriberIdentifierDto | string>;
  /**
   * The name of the topic
   */
  name?: string | undefined;
  /**
   * The preferences of the topic. Can be a simple workflow ID string, workflow preference object, or group filter object
   */
  preferences?:
    | Array<WorkflowPreferenceDto | GroupPreferenceFilterDto | string>
    | undefined;
};

/** @internal */
export type SubscriberIds$Outbound =
  | TopicSubscriberIdentifierDto$Outbound
  | string;

/** @internal */
export const SubscriberIds$outboundSchema: z.ZodType<
  SubscriberIds$Outbound,
  z.ZodTypeDef,
  SubscriberIds
> = z.union([TopicSubscriberIdentifierDto$outboundSchema, z.string()]);

export function subscriberIdsToJSON(subscriberIds: SubscriberIds): string {
  return JSON.stringify(SubscriberIds$outboundSchema.parse(subscriberIds));
}

/** @internal */
export type Preferences$Outbound =
  | WorkflowPreferenceDto$Outbound
  | GroupPreferenceFilterDto$Outbound
  | string;

/** @internal */
export const Preferences$outboundSchema: z.ZodType<
  Preferences$Outbound,
  z.ZodTypeDef,
  Preferences
> = z.union([
  WorkflowPreferenceDto$outboundSchema,
  GroupPreferenceFilterDto$outboundSchema,
  z.string(),
]);

export function preferencesToJSON(preferences: Preferences): string {
  return JSON.stringify(Preferences$outboundSchema.parse(preferences));
}

/** @internal */
export type CreateTopicSubscriptionsRequestDto$Outbound = {
  subscriberIds: Array<TopicSubscriberIdentifierDto$Outbound | string>;
  name?: string | undefined;
  preferences?:
    | Array<
      | WorkflowPreferenceDto$Outbound
      | GroupPreferenceFilterDto$Outbound
      | string
    >
    | undefined;
};

/** @internal */
export const CreateTopicSubscriptionsRequestDto$outboundSchema: z.ZodType<
  CreateTopicSubscriptionsRequestDto$Outbound,
  z.ZodTypeDef,
  CreateTopicSubscriptionsRequestDto
> = z.object({
  subscriberIds: z.array(
    z.union([TopicSubscriberIdentifierDto$outboundSchema, z.string()]),
  ),
  name: z.string().optional(),
  preferences: z.array(
    z.union([
      WorkflowPreferenceDto$outboundSchema,
      GroupPreferenceFilterDto$outboundSchema,
      z.string(),
    ]),
  ).optional(),
});

export function createTopicSubscriptionsRequestDtoToJSON(
  createTopicSubscriptionsRequestDto: CreateTopicSubscriptionsRequestDto,
): string {
  return JSON.stringify(
    CreateTopicSubscriptionsRequestDto$outboundSchema.parse(
      createTopicSubscriptionsRequestDto,
    ),
  );
}
