/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { TimeUnitEnum, TimeUnitEnum$inboundSchema } from "./timeunitenum.js";

export type DigestRegularOutput = {
  /**
   * Amount of time units
   */
  amount: number;
  /**
   * Time unit
   */
  unit: TimeUnitEnum;
  /**
   * Optional digest key
   */
  digestKey?: string | undefined;
  /**
   * Look back window configuration
   */
  lookBackWindow?: { [k: string]: any } | undefined;
};

/** @internal */
export const DigestRegularOutput$inboundSchema: z.ZodType<
  DigestRegularOutput,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: z.number(),
  unit: TimeUnitEnum$inboundSchema,
  digestKey: z.string().optional(),
  lookBackWindow: z.record(z.any()).optional(),
});

export function digestRegularOutputFromJSON(
  jsonString: string,
): SafeParseResult<DigestRegularOutput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DigestRegularOutput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DigestRegularOutput' from JSON`,
  );
}
