/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type FilterDto = {
  /**
   * List of workflow identifiers to filter by
   */
  workflows?: Array<string> | undefined;
  /**
   * List of tags to filter by
   */
  tags?: Array<string> | undefined;
};

/** @internal */
export const FilterDto$inboundSchema: z.ZodType<
  FilterDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  workflows: z.array(z.string()).optional(),
  tags: z.array(z.string()).optional(),
});

/** @internal */
export type FilterDto$Outbound = {
  workflows?: Array<string> | undefined;
  tags?: Array<string> | undefined;
};

/** @internal */
export const FilterDto$outboundSchema: z.ZodType<
  FilterDto$Outbound,
  z.ZodTypeDef,
  FilterDto
> = z.object({
  workflows: z.array(z.string()).optional(),
  tags: z.array(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FilterDto$ {
  /** @deprecated use `FilterDto$inboundSchema` instead. */
  export const inboundSchema = FilterDto$inboundSchema;
  /** @deprecated use `FilterDto$outboundSchema` instead. */
  export const outboundSchema = FilterDto$outboundSchema;
  /** @deprecated use `FilterDto$Outbound` instead. */
  export type Outbound = FilterDto$Outbound;
}

export function filterDtoToJSON(filterDto: FilterDto): string {
  return JSON.stringify(FilterDto$outboundSchema.parse(filterDto));
}

export function filterDtoFromJSON(
  jsonString: string,
): SafeParseResult<FilterDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FilterDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FilterDto' from JSON`,
  );
}
