/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  GroupPreferenceFilterDetailsDto,
  GroupPreferenceFilterDetailsDto$Outbound,
  GroupPreferenceFilterDetailsDto$outboundSchema,
} from "./grouppreferencefilterdetailsdto.js";

export type GroupPreferenceFilterDto = {
  /**
   * Filter criteria for workflow IDs and tags
   */
  filter: GroupPreferenceFilterDetailsDto;
  /**
   * Optional condition using JSON Logic rules
   */
  condition?: { [k: string]: any } | undefined;
};

/** @internal */
export type GroupPreferenceFilterDto$Outbound = {
  filter: GroupPreferenceFilterDetailsDto$Outbound;
  condition?: { [k: string]: any } | undefined;
};

/** @internal */
export const GroupPreferenceFilterDto$outboundSchema: z.ZodType<
  GroupPreferenceFilterDto$Outbound,
  z.ZodTypeDef,
  GroupPreferenceFilterDto
> = z.object({
  filter: GroupPreferenceFilterDetailsDto$outboundSchema,
  condition: z.record(z.any()).optional(),
});

export function groupPreferenceFilterDtoToJSON(
  groupPreferenceFilterDto: GroupPreferenceFilterDto,
): string {
  return JSON.stringify(
    GroupPreferenceFilterDto$outboundSchema.parse(groupPreferenceFilterDto),
  );
}
