/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ObjectT = {};

/** @internal */
export type ObjectT$Outbound = {};

/** @internal */
export const ObjectT$outboundSchema: z.ZodType<
  ObjectT$Outbound,
  z.ZodTypeDef,
  ObjectT
> = z.object({});

export function objectToJSON(objectT: ObjectT): string {
  return JSON.stringify(ObjectT$outboundSchema.parse(objectT));
}
