/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RenameTopicResponseDto = {
  /**
   * Unique identifier for the topic
   */
  id: string;
  /**
   * Identifier for the organization that owns the topic
   */
  organizationId: string;
  /**
   * Identifier for the environment associated with the topic
   */
  environmentId: string;
  /**
   * Key for the topic, used for identifying it uniquely
   */
  key: string;
  /**
   * Name of the topic
   */
  name: string;
  /**
   * List of subscriber IDs for the topic
   */
  subscribers?: Array<string> | undefined;
};

/** @internal */
export const RenameTopicResponseDto$inboundSchema: z.ZodType<
  RenameTopicResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  _id: z.string(),
  _organizationId: z.string(),
  _environmentId: z.string(),
  key: z.string(),
  name: z.string(),
  subscribers: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "_id": "id",
    "_organizationId": "organizationId",
    "_environmentId": "environmentId",
  });
});

/** @internal */
export type RenameTopicResponseDto$Outbound = {
  _id: string;
  _organizationId: string;
  _environmentId: string;
  key: string;
  name: string;
  subscribers?: Array<string> | undefined;
};

/** @internal */
export const RenameTopicResponseDto$outboundSchema: z.ZodType<
  RenameTopicResponseDto$Outbound,
  z.ZodTypeDef,
  RenameTopicResponseDto
> = z.object({
  id: z.string(),
  organizationId: z.string(),
  environmentId: z.string(),
  key: z.string(),
  name: z.string(),
  subscribers: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    id: "_id",
    organizationId: "_organizationId",
    environmentId: "_environmentId",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RenameTopicResponseDto$ {
  /** @deprecated use `RenameTopicResponseDto$inboundSchema` instead. */
  export const inboundSchema = RenameTopicResponseDto$inboundSchema;
  /** @deprecated use `RenameTopicResponseDto$outboundSchema` instead. */
  export const outboundSchema = RenameTopicResponseDto$outboundSchema;
  /** @deprecated use `RenameTopicResponseDto$Outbound` instead. */
  export type Outbound = RenameTopicResponseDto$Outbound;
}

export function renameTopicResponseDtoToJSON(
  renameTopicResponseDto: RenameTopicResponseDto,
): string {
  return JSON.stringify(
    RenameTopicResponseDto$outboundSchema.parse(renameTopicResponseDto),
  );
}

export function renameTopicResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<RenameTopicResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RenameTopicResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RenameTopicResponseDto' from JSON`,
  );
}
