/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SessionGeneratedResponseDto = {
  /**
   * JSON Web Token (JWT) for authentication and authorization in the Inbox service
   */
  jwt: string;
};

/** @internal */
export const SessionGeneratedResponseDto$inboundSchema: z.ZodType<
  SessionGeneratedResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  jwt: z.string(),
});

/** @internal */
export type SessionGeneratedResponseDto$Outbound = {
  jwt: string;
};

/** @internal */
export const SessionGeneratedResponseDto$outboundSchema: z.ZodType<
  SessionGeneratedResponseDto$Outbound,
  z.ZodTypeDef,
  SessionGeneratedResponseDto
> = z.object({
  jwt: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SessionGeneratedResponseDto$ {
  /** @deprecated use `SessionGeneratedResponseDto$inboundSchema` instead. */
  export const inboundSchema = SessionGeneratedResponseDto$inboundSchema;
  /** @deprecated use `SessionGeneratedResponseDto$outboundSchema` instead. */
  export const outboundSchema = SessionGeneratedResponseDto$outboundSchema;
  /** @deprecated use `SessionGeneratedResponseDto$Outbound` instead. */
  export type Outbound = SessionGeneratedResponseDto$Outbound;
}

export function sessionGeneratedResponseDtoToJSON(
  sessionGeneratedResponseDto: SessionGeneratedResponseDto,
): string {
  return JSON.stringify(
    SessionGeneratedResponseDto$outboundSchema.parse(
      sessionGeneratedResponseDto,
    ),
  );
}

export function sessionGeneratedResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<SessionGeneratedResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SessionGeneratedResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SessionGeneratedResponseDto' from JSON`,
  );
}
