/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Override the severity of the workflow
 */
export const SeverityLevelEnum = {
  High: "high",
  Medium: "medium",
  Low: "low",
  None: "none",
} as const;
/**
 * Override the severity of the workflow
 */
export type SeverityLevelEnum = ClosedEnum<typeof SeverityLevelEnum>;

/** @internal */
export const SeverityLevelEnum$inboundSchema: z.ZodNativeEnum<
  typeof SeverityLevelEnum
> = z.nativeEnum(SeverityLevelEnum);
/** @internal */
export const SeverityLevelEnum$outboundSchema: z.ZodNativeEnum<
  typeof SeverityLevelEnum
> = SeverityLevelEnum$inboundSchema;
