/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SubscriptionWorkflowDto = {
  /**
   * The workflow identifier
   */
  id: string;
  /**
   * Whether the workflow is enabled for this subscription
   */
  enabled: boolean;
};

/** @internal */
export const SubscriptionWorkflowDto$inboundSchema: z.ZodType<
  SubscriptionWorkflowDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  enabled: z.boolean(),
});

/** @internal */
export type SubscriptionWorkflowDto$Outbound = {
  id: string;
  enabled: boolean;
};

/** @internal */
export const SubscriptionWorkflowDto$outboundSchema: z.ZodType<
  SubscriptionWorkflowDto$Outbound,
  z.ZodTypeDef,
  SubscriptionWorkflowDto
> = z.object({
  id: z.string(),
  enabled: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SubscriptionWorkflowDto$ {
  /** @deprecated use `SubscriptionWorkflowDto$inboundSchema` instead. */
  export const inboundSchema = SubscriptionWorkflowDto$inboundSchema;
  /** @deprecated use `SubscriptionWorkflowDto$outboundSchema` instead. */
  export const outboundSchema = SubscriptionWorkflowDto$outboundSchema;
  /** @deprecated use `SubscriptionWorkflowDto$Outbound` instead. */
  export type Outbound = SubscriptionWorkflowDto$Outbound;
}

export function subscriptionWorkflowDtoToJSON(
  subscriptionWorkflowDto: SubscriptionWorkflowDto,
): string {
  return JSON.stringify(
    SubscriptionWorkflowDto$outboundSchema.parse(subscriptionWorkflowDto),
  );
}

export function subscriptionWorkflowDtoFromJSON(
  jsonString: string,
): SafeParseResult<SubscriptionWorkflowDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubscriptionWorkflowDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubscriptionWorkflowDto' from JSON`,
  );
}
