/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  FilterDto,
  FilterDto$inboundSchema,
  FilterDto$Outbound,
  FilterDto$outboundSchema,
} from "./filterdto.js";

/**
 * Type of condition rule
 */
export const Type = {
  Checkbox: "checkbox",
  Custom: "custom",
} as const;
/**
 * Type of condition rule
 */
export type Type = ClosedEnum<typeof Type>;

/**
 * JSON Logic condition or boolean value. Supports complex logical operations with AND, OR, and comparison operators. See https://jsonlogic.com/ for full typing reference.
 */
export type Condition = { [k: string]: any } | boolean;

export type TopicSubscriberRuleDto = {
  /**
   * Filter configuration for the rule
   */
  filter?: FilterDto | undefined;
  /**
   * Type of condition rule
   */
  type: Type;
  /**
   * JSON Logic condition or boolean value. Supports complex logical operations with AND, OR, and comparison operators. See https://jsonlogic.com/ for full typing reference.
   */
  condition?: { [k: string]: any } | boolean | undefined;
};

/** @internal */
export const Type$inboundSchema: z.ZodNativeEnum<typeof Type> = z.nativeEnum(
  Type,
);

/** @internal */
export const Type$outboundSchema: z.ZodNativeEnum<typeof Type> =
  Type$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Type$ {
  /** @deprecated use `Type$inboundSchema` instead. */
  export const inboundSchema = Type$inboundSchema;
  /** @deprecated use `Type$outboundSchema` instead. */
  export const outboundSchema = Type$outboundSchema;
}

/** @internal */
export const Condition$inboundSchema: z.ZodType<
  Condition,
  z.ZodTypeDef,
  unknown
> = z.union([z.record(z.any()), z.boolean()]);

/** @internal */
export type Condition$Outbound = { [k: string]: any } | boolean;

/** @internal */
export const Condition$outboundSchema: z.ZodType<
  Condition$Outbound,
  z.ZodTypeDef,
  Condition
> = z.union([z.record(z.any()), z.boolean()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Condition$ {
  /** @deprecated use `Condition$inboundSchema` instead. */
  export const inboundSchema = Condition$inboundSchema;
  /** @deprecated use `Condition$outboundSchema` instead. */
  export const outboundSchema = Condition$outboundSchema;
  /** @deprecated use `Condition$Outbound` instead. */
  export type Outbound = Condition$Outbound;
}

export function conditionToJSON(condition: Condition): string {
  return JSON.stringify(Condition$outboundSchema.parse(condition));
}

export function conditionFromJSON(
  jsonString: string,
): SafeParseResult<Condition, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Condition$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Condition' from JSON`,
  );
}

/** @internal */
export const TopicSubscriberRuleDto$inboundSchema: z.ZodType<
  TopicSubscriberRuleDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  filter: FilterDto$inboundSchema.optional(),
  type: Type$inboundSchema,
  condition: z.union([z.record(z.any()), z.boolean()]).optional(),
});

/** @internal */
export type TopicSubscriberRuleDto$Outbound = {
  filter?: FilterDto$Outbound | undefined;
  type: string;
  condition?: { [k: string]: any } | boolean | undefined;
};

/** @internal */
export const TopicSubscriberRuleDto$outboundSchema: z.ZodType<
  TopicSubscriberRuleDto$Outbound,
  z.ZodTypeDef,
  TopicSubscriberRuleDto
> = z.object({
  filter: FilterDto$outboundSchema.optional(),
  type: Type$outboundSchema,
  condition: z.union([z.record(z.any()), z.boolean()]).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TopicSubscriberRuleDto$ {
  /** @deprecated use `TopicSubscriberRuleDto$inboundSchema` instead. */
  export const inboundSchema = TopicSubscriberRuleDto$inboundSchema;
  /** @deprecated use `TopicSubscriberRuleDto$outboundSchema` instead. */
  export const outboundSchema = TopicSubscriberRuleDto$outboundSchema;
  /** @deprecated use `TopicSubscriberRuleDto$Outbound` instead. */
  export type Outbound = TopicSubscriberRuleDto$Outbound;
}

export function topicSubscriberRuleDtoToJSON(
  topicSubscriberRuleDto: TopicSubscriberRuleDto,
): string {
  return JSON.stringify(
    TopicSubscriberRuleDto$outboundSchema.parse(topicSubscriberRuleDto),
  );
}

export function topicSubscriberRuleDtoFromJSON(
  jsonString: string,
): SafeParseResult<TopicSubscriberRuleDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TopicSubscriberRuleDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TopicSubscriberRuleDto' from JSON`,
  );
}
