/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type TopicSubscriberIdentifierDto = {
  /**
   * Unique identifier for this subscription
   */
  identifier: string;
  /**
   * The subscriber ID
   */
  subscriberId: string;
};

/** @internal */
export type TopicSubscriberIdentifierDto$Outbound = {
  identifier: string;
  subscriberId: string;
};

/** @internal */
export const TopicSubscriberIdentifierDto$outboundSchema: z.ZodType<
  TopicSubscriberIdentifierDto$Outbound,
  z.ZodTypeDef,
  TopicSubscriberIdentifierDto
> = z.object({
  identifier: z.string(),
  subscriberId: z.string(),
});

export function topicSubscriberIdentifierDtoToJSON(
  topicSubscriberIdentifierDto: TopicSubscriberIdentifierDto,
): string {
  return JSON.stringify(
    TopicSubscriberIdentifierDto$outboundSchema.parse(
      topicSubscriberIdentifierDto,
    ),
  );
}
