/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Placeholder5 = string | number | boolean | { [k: string]: any };

/**
 * Placeholder for the UI Schema Property
 */
export type Placeholder =
  | string
  | number
  | boolean
  | { [k: string]: any }
  | Array<string | number | boolean | { [k: string]: any }>;

/**
 * Component type for the UI Schema Property
 */
export const Component = {
  EmailEditorSelect: "EMAIL_EDITOR_SELECT",
  LayoutSelect: "LAYOUT_SELECT",
  BlockEditor: "BLOCK_EDITOR",
  EmailBody: "EMAIL_BODY",
  TextFullLine: "TEXT_FULL_LINE",
  TextInlineLabel: "TEXT_INLINE_LABEL",
  InAppBody: "IN_APP_BODY",
  InAppAvatar: "IN_APP_AVATAR",
  InAppPrimarySubject: "IN_APP_PRIMARY_SUBJECT",
  InAppButtonDropdown: "IN_APP_BUTTON_DROPDOWN",
  InAppDisableSanitizationSwitch: "IN_APP_DISABLE_SANITIZATION_SWITCH",
  DisableSanitizationSwitch: "DISABLE_SANITIZATION_SWITCH",
  UrlTextBox: "URL_TEXT_BOX",
  DigestAmount: "DIGEST_AMOUNT",
  DigestUnit: "DIGEST_UNIT",
  DigestType: "DIGEST_TYPE",
  DigestKey: "DIGEST_KEY",
  DigestCron: "DIGEST_CRON",
  DelayAmount: "DELAY_AMOUNT",
  DelayUnit: "DELAY_UNIT",
  DelayType: "DELAY_TYPE",
  DelayCron: "DELAY_CRON",
  DelayDynamicKey: "DELAY_DYNAMIC_KEY",
  ThrottleType: "THROTTLE_TYPE",
  ThrottleWindow: "THROTTLE_WINDOW",
  ThrottleUnit: "THROTTLE_UNIT",
  ThrottleDynamicKey: "THROTTLE_DYNAMIC_KEY",
  ThrottleThreshold: "THROTTLE_THRESHOLD",
  ThrottleKey: "THROTTLE_KEY",
  ExtendToSchedule: "EXTEND_TO_SCHEDULE",
  SmsBody: "SMS_BODY",
  ChatBody: "CHAT_BODY",
  PushBody: "PUSH_BODY",
  PushSubject: "PUSH_SUBJECT",
  QueryEditor: "QUERY_EDITOR",
  Data: "DATA",
  LayoutEmail: "LAYOUT_EMAIL",
  DestinationMethod: "DESTINATION_METHOD",
  DestinationUrl: "DESTINATION_URL",
  DestinationHeaders: "DESTINATION_HEADERS",
  DestinationBody: "DESTINATION_BODY",
  DestinationResponseBodySchema: "DESTINATION_RESPONSE_BODY_SCHEMA",
  DestinationEnforceSchemaValidation: "DESTINATION_ENFORCE_SCHEMA_VALIDATION",
  DestinationContinueOnFailure: "DESTINATION_CONTINUE_ON_FAILURE",
  DestinationTimeout: "DESTINATION_TIMEOUT",
} as const;
/**
 * Component type for the UI Schema Property
 */
export type Component = OpenEnum<typeof Component>;

export type UiSchemaProperty = {
  /**
   * Placeholder for the UI Schema Property
   */
  placeholder?:
    | string
    | number
    | boolean
    | { [k: string]: any }
    | Array<string | number | boolean | { [k: string]: any }>
    | null
    | undefined;
  /**
   * Component type for the UI Schema Property
   */
  component: Component;
  /**
   * Properties of the UI Schema
   */
  properties?: { [k: string]: UiSchemaProperty } | undefined;
};

/** @internal */
export const Placeholder5$inboundSchema: z.ZodType<
  Placeholder5,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.number(), z.boolean(), z.record(z.any())]);

export function placeholder5FromJSON(
  jsonString: string,
): SafeParseResult<Placeholder5, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Placeholder5$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Placeholder5' from JSON`,
  );
}

/** @internal */
export const Placeholder$inboundSchema: z.ZodType<
  Placeholder,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.record(z.any()),
  z.array(z.union([z.string(), z.number(), z.boolean(), z.record(z.any())])),
]);

export function placeholderFromJSON(
  jsonString: string,
): SafeParseResult<Placeholder, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Placeholder$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Placeholder' from JSON`,
  );
}

/** @internal */
export const Component$inboundSchema: z.ZodType<
  Component,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(Component);

/** @internal */
export const UiSchemaProperty$inboundSchema: z.ZodType<
  UiSchemaProperty,
  z.ZodTypeDef,
  unknown
> = z.object({
  placeholder: z.nullable(
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.any()),
      z.array(
        z.union([z.string(), z.number(), z.boolean(), z.record(z.any())]),
      ),
    ]),
  ).optional(),
  component: Component$inboundSchema,
  properties: z.record(z.lazy(() => UiSchemaProperty$inboundSchema)).optional(),
});

export function uiSchemaPropertyFromJSON(
  jsonString: string,
): SafeParseResult<UiSchemaProperty, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UiSchemaProperty$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UiSchemaProperty' from JSON`,
  );
}
