/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  TopicSubscriberRuleDto,
  TopicSubscriberRuleDto$inboundSchema,
  TopicSubscriberRuleDto$Outbound,
  TopicSubscriberRuleDto$outboundSchema,
} from "./topicsubscriberruledto.js";

export type UpdateTopicSubscriptionRequestDto = {
  /**
   * Rules for conditional subscription. Supports complex logical operations with AND, OR, and comparison operators, or boolean values. See https://jsonlogic.com/ for full typing reference.
   */
  rules?: Array<TopicSubscriberRuleDto> | undefined;
};

/** @internal */
export const UpdateTopicSubscriptionRequestDto$inboundSchema: z.ZodType<
  UpdateTopicSubscriptionRequestDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  rules: z.array(TopicSubscriberRuleDto$inboundSchema).optional(),
});

/** @internal */
export type UpdateTopicSubscriptionRequestDto$Outbound = {
  rules?: Array<TopicSubscriberRuleDto$Outbound> | undefined;
};

/** @internal */
export const UpdateTopicSubscriptionRequestDto$outboundSchema: z.ZodType<
  UpdateTopicSubscriptionRequestDto$Outbound,
  z.ZodTypeDef,
  UpdateTopicSubscriptionRequestDto
> = z.object({
  rules: z.array(TopicSubscriberRuleDto$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateTopicSubscriptionRequestDto$ {
  /** @deprecated use `UpdateTopicSubscriptionRequestDto$inboundSchema` instead. */
  export const inboundSchema = UpdateTopicSubscriptionRequestDto$inboundSchema;
  /** @deprecated use `UpdateTopicSubscriptionRequestDto$outboundSchema` instead. */
  export const outboundSchema =
    UpdateTopicSubscriptionRequestDto$outboundSchema;
  /** @deprecated use `UpdateTopicSubscriptionRequestDto$Outbound` instead. */
  export type Outbound = UpdateTopicSubscriptionRequestDto$Outbound;
}

export function updateTopicSubscriptionRequestDtoToJSON(
  updateTopicSubscriptionRequestDto: UpdateTopicSubscriptionRequestDto,
): string {
  return JSON.stringify(
    UpdateTopicSubscriptionRequestDto$outboundSchema.parse(
      updateTopicSubscriptionRequestDto,
    ),
  );
}

export function updateTopicSubscriptionRequestDtoFromJSON(
  jsonString: string,
): SafeParseResult<UpdateTopicSubscriptionRequestDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateTopicSubscriptionRequestDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateTopicSubscriptionRequestDto' from JSON`,
  );
}
