/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type WorkflowPreferenceDto = {
  /**
   * Whether the preference is enabled. Used when condition is not provided.
   */
  enabled?: boolean | undefined;
  /**
   * Optional condition using JSON Logic rules
   */
  condition?: { [k: string]: any } | undefined;
  /**
   * The workflow identifier
   */
  workflowId: string;
};

/** @internal */
export const WorkflowPreferenceDto$inboundSchema: z.ZodType<
  WorkflowPreferenceDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  enabled: z.boolean().optional(),
  condition: z.record(z.any()).optional(),
  workflowId: z.string(),
});
/** @internal */
export type WorkflowPreferenceDto$Outbound = {
  enabled?: boolean | undefined;
  condition?: { [k: string]: any } | undefined;
  workflowId: string;
};

/** @internal */
export const WorkflowPreferenceDto$outboundSchema: z.ZodType<
  WorkflowPreferenceDto$Outbound,
  z.ZodTypeDef,
  WorkflowPreferenceDto
> = z.object({
  enabled: z.boolean().optional(),
  condition: z.record(z.any()).optional(),
  workflowId: z.string(),
});

export function workflowPreferenceDtoToJSON(
  workflowPreferenceDto: WorkflowPreferenceDto,
): string {
  return JSON.stringify(
    WorkflowPreferenceDto$outboundSchema.parse(workflowPreferenceDto),
  );
}
export function workflowPreferenceDtoFromJSON(
  jsonString: string,
): SafeParseResult<WorkflowPreferenceDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorkflowPreferenceDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorkflowPreferenceDto' from JSON`,
  );
}
