/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { NovuCore } from "../core.js";
import { environmentsEnvironmentsControllerGenerateSession } from "../funcs/environmentsEnvironmentsControllerGenerateSession.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useNovuContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type EnvironmentsEnvironmentsControllerGenerateSessionMutationVariables =
  {
    subscriberId: string;
    idempotencyKey?: string | undefined;
    options?: RequestOptions;
  };

export type EnvironmentsEnvironmentsControllerGenerateSessionMutationData =
  operations.EnvironmentsControllerGenerateSessionResponse;

export function useEnvironmentsEnvironmentsControllerGenerateSessionMutation(
  options?: MutationHookOptions<
    EnvironmentsEnvironmentsControllerGenerateSessionMutationData,
    Error,
    EnvironmentsEnvironmentsControllerGenerateSessionMutationVariables
  >,
): UseMutationResult<
  EnvironmentsEnvironmentsControllerGenerateSessionMutationData,
  Error,
  EnvironmentsEnvironmentsControllerGenerateSessionMutationVariables
> {
  const client = useNovuContext();
  return useMutation({
    ...buildEnvironmentsEnvironmentsControllerGenerateSessionMutation(
      client,
      options,
    ),
    ...options,
  });
}

export function mutationKeyEnvironmentsEnvironmentsControllerGenerateSession(): MutationKey {
  return ["@novu/api", "Environments", "environmentsControllerGenerateSession"];
}

export function buildEnvironmentsEnvironmentsControllerGenerateSessionMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables:
      EnvironmentsEnvironmentsControllerGenerateSessionMutationVariables,
  ) => Promise<EnvironmentsEnvironmentsControllerGenerateSessionMutationData>;
} {
  return {
    mutationKey: mutationKeyEnvironmentsEnvironmentsControllerGenerateSession(),
    mutationFn:
      function environmentsEnvironmentsControllerGenerateSessionMutationFn({
        subscriberId,
        idempotencyKey,
        options,
      }): Promise<
        EnvironmentsEnvironmentsControllerGenerateSessionMutationData
      > {
        const mergedOptions = {
          ...hookOptions,
          ...options,
          fetchOptions: {
            ...hookOptions?.fetchOptions,
            ...options?.fetchOptions,
            signal: combineSignals(
              hookOptions?.fetchOptions?.signal,
              options?.fetchOptions?.signal,
            ),
          },
        };
        return unwrapAsync(environmentsEnvironmentsControllerGenerateSession(
          client$,
          subscriberId,
          idempotencyKey,
          mergedOptions,
        ));
      },
  };
}
