/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { NovuCore } from "../core.js";
import { environmentsGenerateSession } from "../funcs/environmentsGenerateSession.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useNovuContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type EnvironmentsGenerateSessionMutationVariables = {
  subscriberId: string;
  idempotencyKey?: string | undefined;
  options?: RequestOptions;
};

export type EnvironmentsGenerateSessionMutationData =
  operations.EnvironmentsControllerGenerateSessionResponse;

export function useEnvironmentsGenerateSessionMutation(
  options?: MutationHookOptions<
    EnvironmentsGenerateSessionMutationData,
    Error,
    EnvironmentsGenerateSessionMutationVariables
  >,
): UseMutationResult<
  EnvironmentsGenerateSessionMutationData,
  Error,
  EnvironmentsGenerateSessionMutationVariables
> {
  const client = useNovuContext();
  return useMutation({
    ...buildEnvironmentsGenerateSessionMutation(client, options),
    ...options,
  });
}

export function mutationKeyEnvironmentsGenerateSession(): MutationKey {
  return ["@novu/api", "Environments", "generateSession"];
}

export function buildEnvironmentsGenerateSessionMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: EnvironmentsGenerateSessionMutationVariables,
  ) => Promise<EnvironmentsGenerateSessionMutationData>;
} {
  return {
    mutationKey: mutationKeyEnvironmentsGenerateSession(),
    mutationFn: function environmentsGenerateSessionMutationFn({
      subscriberId,
      idempotencyKey,
      options,
    }): Promise<EnvironmentsGenerateSessionMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(environmentsGenerateSession(
        client$,
        subscriberId,
        idempotencyKey,
        mergedOptions,
      ));
    },
  };
}
