/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { NovuCore } from "../core.js";
import { environmentsRetrieve } from "../funcs/environmentsRetrieve.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useNovuContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";

export type EnvironmentsRetrieveQueryData =
  operations.EnvironmentsControllerGetEnvironmentTagsResponse;

export function useEnvironmentsRetrieve(
  environmentId: string,
  idempotencyKey?: string | undefined,
  options?: QueryHookOptions<EnvironmentsRetrieveQueryData>,
): UseQueryResult<EnvironmentsRetrieveQueryData, Error> {
  const client = useNovuContext();
  return useQuery({
    ...buildEnvironmentsRetrieveQuery(
      client,
      environmentId,
      idempotencyKey,
      options,
    ),
    ...options,
  });
}

export function useEnvironmentsRetrieveSuspense(
  environmentId: string,
  idempotencyKey?: string | undefined,
  options?: SuspenseQueryHookOptions<EnvironmentsRetrieveQueryData>,
): UseSuspenseQueryResult<EnvironmentsRetrieveQueryData, Error> {
  const client = useNovuContext();
  return useSuspenseQuery({
    ...buildEnvironmentsRetrieveQuery(
      client,
      environmentId,
      idempotencyKey,
      options,
    ),
    ...options,
  });
}

export function prefetchEnvironmentsRetrieve(
  queryClient: QueryClient,
  client$: NovuCore,
  environmentId: string,
  idempotencyKey?: string | undefined,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildEnvironmentsRetrieveQuery(
      client$,
      environmentId,
      idempotencyKey,
    ),
  });
}

export function setEnvironmentsRetrieveData(
  client: QueryClient,
  queryKeyBase: [
    environmentId: string,
    parameters: { idempotencyKey?: string | undefined },
  ],
  data: EnvironmentsRetrieveQueryData,
): EnvironmentsRetrieveQueryData | undefined {
  const key = queryKeyEnvironmentsRetrieve(...queryKeyBase);

  return client.setQueryData<EnvironmentsRetrieveQueryData>(key, data);
}

export function invalidateEnvironmentsRetrieve(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [environmentId: string, parameters: { idempotencyKey?: string | undefined }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@novu/api", "Environments", "retrieve", ...queryKeyBase],
  });
}

export function invalidateAllEnvironmentsRetrieve(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@novu/api", "Environments", "retrieve"],
  });
}

export function buildEnvironmentsRetrieveQuery(
  client$: NovuCore,
  environmentId: string,
  idempotencyKey?: string | undefined,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<EnvironmentsRetrieveQueryData>;
} {
  return {
    queryKey: queryKeyEnvironmentsRetrieve(environmentId, { idempotencyKey }),
    queryFn: async function environmentsRetrieveQueryFn(
      ctx,
    ): Promise<EnvironmentsRetrieveQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(environmentsRetrieve(
        client$,
        environmentId,
        idempotencyKey,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyEnvironmentsRetrieve(
  environmentId: string,
  parameters: { idempotencyKey?: string | undefined },
): QueryKey {
  return ["@novu/api", "Environments", "retrieve", environmentId, parameters];
}
