/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { NovuCore } from "../core.js";
import { environmentsCreate } from "../funcs/environmentsCreate.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { CreateEnvironmentRequestDto } from "../models/components/createenvironmentrequestdto.js";
import { EnvironmentsControllerV1CreateEnvironmentResponse } from "../models/operations/environmentscontrollerv1createenvironment.js";
import { unwrapAsync } from "../types/fp.js";
import { useNovuContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type EnvironmentsCreateMutationVariables = {
  createEnvironmentRequestDto: CreateEnvironmentRequestDto;
  idempotencyKey?: string | undefined;
  options?: RequestOptions;
};

export type EnvironmentsCreateMutationData =
  EnvironmentsControllerV1CreateEnvironmentResponse;

/**
 * Create environment
 */
export function useEnvironmentsCreateMutation(
  options?: MutationHookOptions<
    EnvironmentsCreateMutationData,
    Error,
    EnvironmentsCreateMutationVariables
  >,
): UseMutationResult<
  EnvironmentsCreateMutationData,
  Error,
  EnvironmentsCreateMutationVariables
> {
  const client = useNovuContext();
  return useMutation({
    ...buildEnvironmentsCreateMutation(client, options),
    ...options,
  });
}

export function mutationKeyEnvironmentsCreate(): MutationKey {
  return ["@novu/api", "Environments", "create"];
}

export function buildEnvironmentsCreateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: EnvironmentsCreateMutationVariables,
  ) => Promise<EnvironmentsCreateMutationData>;
} {
  return {
    mutationKey: mutationKeyEnvironmentsCreate(),
    mutationFn: function environmentsCreateMutationFn({
      createEnvironmentRequestDto,
      idempotencyKey,
      options,
    }): Promise<EnvironmentsCreateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(environmentsCreate(
        client$,
        createEnvironmentRequestDto,
        idempotencyKey,
        mergedOptions,
      ));
    },
  };
}
