/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { NovuCore } from "../core.js";
import { integrationsUpdate } from "../funcs/integrationsUpdate.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { UpdateIntegrationRequestDto } from "../models/components/updateintegrationrequestdto.js";
import { IntegrationsControllerUpdateIntegrationByIdResponse } from "../models/operations/integrationscontrollerupdateintegrationbyid.js";
import { unwrapAsync } from "../types/fp.js";
import { useNovuContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type IntegrationsUpdateMutationVariables = {
  updateIntegrationRequestDto: UpdateIntegrationRequestDto;
  integrationId: string;
  idempotencyKey?: string | undefined;
  options?: RequestOptions;
};

export type IntegrationsUpdateMutationData =
  IntegrationsControllerUpdateIntegrationByIdResponse;

/**
 * Update integration
 */
export function useIntegrationsUpdateMutation(
  options?: MutationHookOptions<
    IntegrationsUpdateMutationData,
    Error,
    IntegrationsUpdateMutationVariables
  >,
): UseMutationResult<
  IntegrationsUpdateMutationData,
  Error,
  IntegrationsUpdateMutationVariables
> {
  const client = useNovuContext();
  return useMutation({
    ...buildIntegrationsUpdateMutation(client, options),
    ...options,
  });
}

export function mutationKeyIntegrationsUpdate(): MutationKey {
  return ["@novu/api", "Integrations", "update"];
}

export function buildIntegrationsUpdateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: IntegrationsUpdateMutationVariables,
  ) => Promise<IntegrationsUpdateMutationData>;
} {
  return {
    mutationKey: mutationKeyIntegrationsUpdate(),
    mutationFn: function integrationsUpdateMutationFn({
      updateIntegrationRequestDto,
      integrationId,
      idempotencyKey,
      options,
    }): Promise<IntegrationsUpdateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(integrationsUpdate(
        client$,
        updateIntegrationRequestDto,
        integrationId,
        idempotencyKey,
        mergedOptions,
      ));
    },
  };
}
