/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { NovuCore } from "../core.js";
import { subscribersCredentialsAppend } from "../funcs/subscribersCredentialsAppend.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { UpdateSubscriberChannelRequestDto } from "../models/components/updatesubscriberchannelrequestdto.js";
import { SubscribersV1ControllerModifySubscriberChannelResponse } from "../models/operations/subscribersv1controllermodifysubscriberchannel.js";
import { unwrapAsync } from "../types/fp.js";
import { useNovuContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type SubscribersCredentialsAppendMutationVariables = {
  updateSubscriberChannelRequestDto: UpdateSubscriberChannelRequestDto;
  subscriberId: string;
  idempotencyKey?: string | undefined;
  options?: RequestOptions;
};

export type SubscribersCredentialsAppendMutationData =
  SubscribersV1ControllerModifySubscriberChannelResponse;

/**
 * Modify subscriber credentials
 *
 * @remarks
 * Subscriber credentials associated to the delivery methods such as slack and push tokens.
 *     This endpoint appends provided credentials and deviceTokens to the existing ones.
 */
export function useSubscribersCredentialsAppendMutation(
  options?: MutationHookOptions<
    SubscribersCredentialsAppendMutationData,
    Error,
    SubscribersCredentialsAppendMutationVariables
  >,
): UseMutationResult<
  SubscribersCredentialsAppendMutationData,
  Error,
  SubscribersCredentialsAppendMutationVariables
> {
  const client = useNovuContext();
  return useMutation({
    ...buildSubscribersCredentialsAppendMutation(client, options),
    ...options,
  });
}

export function mutationKeySubscribersCredentialsAppend(): MutationKey {
  return ["@novu/api", "Credentials", "append"];
}

export function buildSubscribersCredentialsAppendMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: SubscribersCredentialsAppendMutationVariables,
  ) => Promise<SubscribersCredentialsAppendMutationData>;
} {
  return {
    mutationKey: mutationKeySubscribersCredentialsAppend(),
    mutationFn: function subscribersCredentialsAppendMutationFn({
      updateSubscriberChannelRequestDto,
      subscriberId,
      idempotencyKey,
      options,
    }): Promise<SubscribersCredentialsAppendMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(subscribersCredentialsAppend(
        client$,
        updateSubscriberChannelRequestDto,
        subscriberId,
        idempotencyKey,
        mergedOptions,
      ));
    },
  };
}
