/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { NovuCore } from "../core.js";
import { subscribersMessagesMarkAllAs } from "../funcs/subscribersMessagesMarkAllAs.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { MessageMarkAsRequestDto } from "../models/components/messagemarkasrequestdto.js";
import { SubscribersV1ControllerMarkMessagesAsResponse } from "../models/operations/subscribersv1controllermarkmessagesas.js";
import { unwrapAsync } from "../types/fp.js";
import { useNovuContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type SubscribersMessagesMarkAllAsMutationVariables = {
  messageMarkAsRequestDto: MessageMarkAsRequestDto;
  subscriberId: string;
  idempotencyKey?: string | undefined;
  options?: RequestOptions;
};

export type SubscribersMessagesMarkAllAsMutationData =
  SubscribersV1ControllerMarkMessagesAsResponse;

/**
 * Mark a subscriber messages as seen, read, unseen or unread
 */
export function useSubscribersMessagesMarkAllAsMutation(
  options?: MutationHookOptions<
    SubscribersMessagesMarkAllAsMutationData,
    Error,
    SubscribersMessagesMarkAllAsMutationVariables
  >,
): UseMutationResult<
  SubscribersMessagesMarkAllAsMutationData,
  Error,
  SubscribersMessagesMarkAllAsMutationVariables
> {
  const client = useNovuContext();
  return useMutation({
    ...buildSubscribersMessagesMarkAllAsMutation(client, options),
    ...options,
  });
}

export function mutationKeySubscribersMessagesMarkAllAs(): MutationKey {
  return ["@novu/api", "Messages", "markAllAs"];
}

export function buildSubscribersMessagesMarkAllAsMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: SubscribersMessagesMarkAllAsMutationVariables,
  ) => Promise<SubscribersMessagesMarkAllAsMutationData>;
} {
  return {
    mutationKey: mutationKeySubscribersMessagesMarkAllAs(),
    mutationFn: function subscribersMessagesMarkAllAsMutationFn({
      messageMarkAsRequestDto,
      subscriberId,
      idempotencyKey,
      options,
    }): Promise<SubscribersMessagesMarkAllAsMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(subscribersMessagesMarkAllAs(
        client$,
        messageMarkAsRequestDto,
        subscriberId,
        idempotencyKey,
        mergedOptions,
      ));
    },
  };
}
