/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { type MutationKey, type UseMutationResult, useMutation } from '@tanstack/react-query';
import type { NovuCore } from '../core.js';
import { subscribersCreate } from '../funcs/subscribersCreate.js';
import { combineSignals } from '../lib/primitives.js';
import type { RequestOptions } from '../lib/sdks.js';
import type * as components from '../models/components/index.js';
import type * as operations from '../models/operations/index.js';
import { unwrapAsync } from '../types/fp.js';
import { useNovuContext } from './_context.js';
import type { MutationHookOptions } from './_types.js';

export type SubscribersCreateMutationVariables = {
  createSubscriberRequestDto: components.CreateSubscriberRequestDto;
  idempotencyKey?: string | undefined;
  options?: RequestOptions;
};

export type SubscribersCreateMutationData = operations.SubscribersControllerCreateSubscriberResponse;

/**
 * Create a subscriber
 *
 * @remarks
 * Create a subscriber with the subscriber attributes.
 *       **subscriberId** is a required field, rest other fields are optional, if the subscriber already exists, it will be updated
 */
export function useSubscribersCreateMutation(
  options?: MutationHookOptions<SubscribersCreateMutationData, Error, SubscribersCreateMutationVariables>
): UseMutationResult<SubscribersCreateMutationData, Error, SubscribersCreateMutationVariables> {
  const client = useNovuContext();
  return useMutation({
    ...buildSubscribersCreateMutation(client, options),
    ...options,
  });
}

export function mutationKeySubscribersCreate(): MutationKey {
  return ['@novu/api', 'Subscribers', 'create'];
}

export function buildSubscribersCreateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions
): {
  mutationKey: MutationKey;
  mutationFn: (variables: SubscribersCreateMutationVariables) => Promise<SubscribersCreateMutationData>;
} {
  return {
    mutationKey: mutationKeySubscribersCreate(),
    mutationFn: function subscribersCreateMutationFn({
      createSubscriberRequestDto,
      idempotencyKey,
      options,
    }): Promise<SubscribersCreateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(hookOptions?.fetchOptions?.signal, options?.fetchOptions?.signal),
        },
      };
      return unwrapAsync(subscribersCreate(client$, createSubscriberRequestDto, idempotencyKey, mergedOptions));
    },
  };
}
