/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { NovuCore } from "../core.js";
import { subscribersPropertiesUpdateOnlineFlag } from "../funcs/subscribersPropertiesUpdateOnlineFlag.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { UpdateSubscriberOnlineFlagRequestDto } from "../models/components/updatesubscriberonlineflagrequestdto.js";
import { SubscribersV1ControllerUpdateSubscriberOnlineFlagResponse } from "../models/operations/subscribersv1controllerupdatesubscriberonlineflag.js";
import { unwrapAsync } from "../types/fp.js";
import { useNovuContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type SubscribersPropertiesUpdateOnlineFlagMutationVariables = {
  updateSubscriberOnlineFlagRequestDto: UpdateSubscriberOnlineFlagRequestDto;
  subscriberId: string;
  idempotencyKey?: string | undefined;
  options?: RequestOptions;
};

export type SubscribersPropertiesUpdateOnlineFlagMutationData =
  SubscribersV1ControllerUpdateSubscriberOnlineFlagResponse;

/**
 * Update subscriber online status
 *
 * @remarks
 * Used to update the subscriber isOnline flag.
 */
export function useSubscribersPropertiesUpdateOnlineFlagMutation(
  options?: MutationHookOptions<
    SubscribersPropertiesUpdateOnlineFlagMutationData,
    Error,
    SubscribersPropertiesUpdateOnlineFlagMutationVariables
  >,
): UseMutationResult<
  SubscribersPropertiesUpdateOnlineFlagMutationData,
  Error,
  SubscribersPropertiesUpdateOnlineFlagMutationVariables
> {
  const client = useNovuContext();
  return useMutation({
    ...buildSubscribersPropertiesUpdateOnlineFlagMutation(client, options),
    ...options,
  });
}

export function mutationKeySubscribersPropertiesUpdateOnlineFlag(): MutationKey {
  return ["@novu/api", "properties", "updateOnlineFlag"];
}

export function buildSubscribersPropertiesUpdateOnlineFlagMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: SubscribersPropertiesUpdateOnlineFlagMutationVariables,
  ) => Promise<SubscribersPropertiesUpdateOnlineFlagMutationData>;
} {
  return {
    mutationKey: mutationKeySubscribersPropertiesUpdateOnlineFlag(),
    mutationFn: function subscribersPropertiesUpdateOnlineFlagMutationFn({
      updateSubscriberOnlineFlagRequestDto,
      subscriberId,
      idempotencyKey,
      options,
    }): Promise<SubscribersPropertiesUpdateOnlineFlagMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(subscribersPropertiesUpdateOnlineFlag(
        client$,
        updateSubscriberOnlineFlagRequestDto,
        subscriberId,
        idempotencyKey,
        mergedOptions,
      ));
    },
  };
}
