/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { NovuCore } from "../core.js";
import { topicsSubscribersAssign } from "../funcs/topicsSubscribersAssign.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { AddSubscribersRequestDto } from "../models/components/addsubscribersrequestdto.js";
import { TopicsControllerAssignResponse } from "../models/operations/topicscontrollerassign.js";
import { unwrapAsync } from "../types/fp.js";
import { useNovuContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type TopicsSubscribersAssignMutationVariables = {
  addSubscribersRequestDto: AddSubscribersRequestDto;
  topicKey: string;
  idempotencyKey?: string | undefined;
  options?: RequestOptions;
};

export type TopicsSubscribersAssignMutationData =
  TopicsControllerAssignResponse;

/**
 * Subscribers addition
 *
 * @remarks
 * Add subscribers to a topic by key
 */
export function useTopicsSubscribersAssignMutation(
  options?: MutationHookOptions<
    TopicsSubscribersAssignMutationData,
    Error,
    TopicsSubscribersAssignMutationVariables
  >,
): UseMutationResult<
  TopicsSubscribersAssignMutationData,
  Error,
  TopicsSubscribersAssignMutationVariables
> {
  const client = useNovuContext();
  return useMutation({
    ...buildTopicsSubscribersAssignMutation(client, options),
    ...options,
  });
}

export function mutationKeyTopicsSubscribersAssign(): MutationKey {
  return ["@novu/api", "Subscribers", "assign"];
}

export function buildTopicsSubscribersAssignMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: TopicsSubscribersAssignMutationVariables,
  ) => Promise<TopicsSubscribersAssignMutationData>;
} {
  return {
    mutationKey: mutationKeyTopicsSubscribersAssign(),
    mutationFn: function topicsSubscribersAssignMutationFn({
      addSubscribersRequestDto,
      topicKey,
      idempotencyKey,
      options,
    }): Promise<TopicsSubscribersAssignMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(topicsSubscribersAssign(
        client$,
        addSubscribersRequestDto,
        topicKey,
        idempotencyKey,
        mergedOptions,
      ));
    },
  };
}
