/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscribersAuthenticationChatAccessOauth } from "../funcs/subscribersAuthenticationChatAccessOauth.js";
import {
  ChatAccessOauthCallBackAcceptEnum,
  subscribersAuthenticationChatAccessOauthCallBack,
} from "../funcs/subscribersAuthenticationChatAccessOauthCallBack.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import {
  SubscribersV1ControllerChatAccessOauthRequest,
  SubscribersV1ControllerChatAccessOauthResponse,
} from "../models/operations/subscribersv1controllerchataccessoauth.js";
import {
  SubscribersV1ControllerChatOauthCallbackRequest,
  SubscribersV1ControllerChatOauthCallbackResponse,
} from "../models/operations/subscribersv1controllerchatoauthcallback.js";
import { unwrapAsync } from "../types/fp.js";

export { ChatAccessOauthCallBackAcceptEnum } from "../funcs/subscribersAuthenticationChatAccessOauthCallBack.js";

export class Authentication extends ClientSDK {
  /**
   * Handle chat oauth
   */
  async chatAccessOauth(
    request: SubscribersV1ControllerChatAccessOauthRequest,
    options?: RequestOptions,
  ): Promise<SubscribersV1ControllerChatAccessOauthResponse | undefined> {
    return unwrapAsync(subscribersAuthenticationChatAccessOauth(
      this,
      request,
      options,
    ));
  }

  /**
   * Handle providers oauth redirect
   */
  async chatAccessOauthCallBack(
    request: SubscribersV1ControllerChatOauthCallbackRequest,
    options?: RequestOptions & {
      acceptHeaderOverride?: ChatAccessOauthCallBackAcceptEnum;
    },
  ): Promise<SubscribersV1ControllerChatOauthCallbackResponse> {
    return unwrapAsync(subscribersAuthenticationChatAccessOauthCallBack(
      this,
      request,
      options,
    ));
  }
}
