/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscribersCredentialsAppend } from "../funcs/subscribersCredentialsAppend.js";
import { subscribersCredentialsDelete } from "../funcs/subscribersCredentialsDelete.js";
import { subscribersCredentialsUpdate } from "../funcs/subscribersCredentialsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { UpdateSubscriberChannelRequestDto } from "../models/components/updatesubscriberchannelrequestdto.js";
import { SubscribersV1ControllerDeleteSubscriberCredentialsResponse } from "../models/operations/subscribersv1controllerdeletesubscribercredentials.js";
import { SubscribersV1ControllerModifySubscriberChannelResponse } from "../models/operations/subscribersv1controllermodifysubscriberchannel.js";
import { SubscribersV1ControllerUpdateSubscriberChannelResponse } from "../models/operations/subscribersv1controllerupdatesubscriberchannel.js";
import { unwrapAsync } from "../types/fp.js";

export class Credentials extends ClientSDK {
  /**
   * Update subscriber credentials
   *
   * @remarks
   * Subscriber credentials associated to the delivery methods such as slack and push tokens.
   */
  async update(
    updateSubscriberChannelRequestDto: UpdateSubscriberChannelRequestDto,
    subscriberId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<SubscribersV1ControllerUpdateSubscriberChannelResponse> {
    return unwrapAsync(subscribersCredentialsUpdate(
      this,
      updateSubscriberChannelRequestDto,
      subscriberId,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Modify subscriber credentials
   *
   * @remarks
   * Subscriber credentials associated to the delivery methods such as slack and push tokens.
   *     This endpoint appends provided credentials and deviceTokens to the existing ones.
   */
  async append(
    updateSubscriberChannelRequestDto: UpdateSubscriberChannelRequestDto,
    subscriberId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<SubscribersV1ControllerModifySubscriberChannelResponse> {
    return unwrapAsync(subscribersCredentialsAppend(
      this,
      updateSubscriberChannelRequestDto,
      subscriberId,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Delete subscriber credentials by providerId
   *
   * @remarks
   * Delete subscriber credentials such as slack and expo tokens.
   */
  async delete(
    subscriberId: string,
    providerId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<
    SubscribersV1ControllerDeleteSubscriberCredentialsResponse | undefined
  > {
    return unwrapAsync(subscribersCredentialsDelete(
      this,
      subscriberId,
      providerId,
      idempotencyKey,
      options,
    ));
  }
}
