/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { environmentsCreate } from "../funcs/environmentsCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { CreateEnvironmentRequestDto } from "../models/components/createenvironmentrequestdto.js";
import { EnvironmentsControllerV1CreateEnvironmentResponse } from "../models/operations/environmentscontrollerv1createenvironment.js";
import { unwrapAsync } from "../types/fp.js";

export class Environments extends ClientSDK {
  /**
   * Create environment
   */
  async create(
    createEnvironmentRequestDto: CreateEnvironmentRequestDto,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<EnvironmentsControllerV1CreateEnvironmentResponse> {
    return unwrapAsync(environmentsCreate(
      this,
      createEnvironmentRequestDto,
      idempotencyKey,
      options,
    ));
  }
}
