/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { environmentsEnvironmentsControllerGenerateSession } from "../funcs/environmentsEnvironmentsControllerGenerateSession.js";
import { environmentsRetrieve } from "../funcs/environmentsRetrieve.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Environments extends ClientSDK {
  /**
   * Get topic
   *
   * @remarks
   * Get a topic by its topic key
   */
  async retrieve(
    environmentId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.EnvironmentsControllerGetEnvironmentTagsResponse> {
    return unwrapAsync(environmentsRetrieve(
      this,
      environmentId,
      idempotencyKey,
      options,
    ));
  }

  async environmentsControllerGenerateSession(
    subscriberId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.EnvironmentsControllerGenerateSessionResponse> {
    return unwrapAsync(environmentsEnvironmentsControllerGenerateSession(
      this,
      subscriberId,
      idempotencyKey,
      options,
    ));
  }
}
