/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsCreate } from "../funcs/integrationsCreate.js";
import { integrationsDelete } from "../funcs/integrationsDelete.js";
import { integrationsList } from "../funcs/integrationsList.js";
import { integrationsListActive } from "../funcs/integrationsListActive.js";
import { integrationsSetAsPrimary } from "../funcs/integrationsSetAsPrimary.js";
import { integrationsUpdate } from "../funcs/integrationsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { CreateIntegrationRequestDto } from "../models/components/createintegrationrequestdto.js";
import { UpdateIntegrationRequestDto } from "../models/components/updateintegrationrequestdto.js";
import { IntegrationsControllerCreateIntegrationResponse } from "../models/operations/integrationscontrollercreateintegration.js";
import { IntegrationsControllerGetActiveIntegrationsResponse } from "../models/operations/integrationscontrollergetactiveintegrations.js";
import { IntegrationsControllerListIntegrationsResponse } from "../models/operations/integrationscontrollerlistintegrations.js";
import { IntegrationsControllerRemoveIntegrationResponse } from "../models/operations/integrationscontrollerremoveintegration.js";
import { IntegrationsControllerSetIntegrationAsPrimaryResponse } from "../models/operations/integrationscontrollersetintegrationasprimary.js";
import { IntegrationsControllerUpdateIntegrationByIdResponse } from "../models/operations/integrationscontrollerupdateintegrationbyid.js";
import { unwrapAsync } from "../types/fp.js";
import { Webhooks } from "./webhooks.js";

export class Integrations extends ClientSDK {
  private _webhooks?: Webhooks;
  get webhooks(): Webhooks {
    return (this._webhooks ??= new Webhooks(this._options));
  }

  /**
   * Get integrations
   *
   * @remarks
   * Return all the integrations the user has created for that organization. Review v.0.17.0 changelog for a breaking change
   */
  async list(
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<IntegrationsControllerListIntegrationsResponse> {
    return unwrapAsync(integrationsList(
      this,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Create integration
   *
   * @remarks
   * Create an integration for the current environment the user is based on the API key provided
   */
  async create(
    createIntegrationRequestDto: CreateIntegrationRequestDto,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<IntegrationsControllerCreateIntegrationResponse> {
    return unwrapAsync(integrationsCreate(
      this,
      createIntegrationRequestDto,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Update integration
   */
  async update(
    updateIntegrationRequestDto: UpdateIntegrationRequestDto,
    integrationId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<IntegrationsControllerUpdateIntegrationByIdResponse> {
    return unwrapAsync(integrationsUpdate(
      this,
      updateIntegrationRequestDto,
      integrationId,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Delete integration
   */
  async delete(
    integrationId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<IntegrationsControllerRemoveIntegrationResponse> {
    return unwrapAsync(integrationsDelete(
      this,
      integrationId,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Set integration as primary
   */
  async setAsPrimary(
    integrationId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<IntegrationsControllerSetIntegrationAsPrimaryResponse> {
    return unwrapAsync(integrationsSetAsPrimary(
      this,
      integrationId,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Get active integrations
   *
   * @remarks
   * Return all the active integrations the user has created for that organization. Review v.0.17.0 changelog for a breaking change
   */
  async listActive(
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<IntegrationsControllerGetActiveIntegrationsResponse> {
    return unwrapAsync(integrationsListActive(
      this,
      idempotencyKey,
      options,
    ));
  }
}
