/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { topicsSubscribersAssign } from "../funcs/topicsSubscribersAssign.js";
import { topicsSubscribersRemove } from "../funcs/topicsSubscribersRemove.js";
import { topicsSubscribersRetrieve } from "../funcs/topicsSubscribersRetrieve.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { AddSubscribersRequestDto } from "../models/components/addsubscribersrequestdto.js";
import { RemoveSubscribersRequestDto } from "../models/components/removesubscribersrequestdto.js";
import { TopicsControllerAssignResponse } from "../models/operations/topicscontrollerassign.js";
import { TopicsControllerGetTopicSubscriberResponse } from "../models/operations/topicscontrollergettopicsubscriber.js";
import { TopicsControllerRemoveSubscribersResponse } from "../models/operations/topicscontrollerremovesubscribers.js";
import { unwrapAsync } from "../types/fp.js";

export class NovuSubscribers extends ClientSDK {
  /**
   * Subscribers addition
   *
   * @remarks
   * Add subscribers to a topic by key
   */
  async assign(
    addSubscribersRequestDto: AddSubscribersRequestDto,
    topicKey: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<TopicsControllerAssignResponse> {
    return unwrapAsync(topicsSubscribersAssign(
      this,
      addSubscribersRequestDto,
      topicKey,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Check topic subscriber
   *
   * @remarks
   * Check if a subscriber belongs to a certain topic
   */
  async retrieve(
    topicKey: string,
    externalSubscriberId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<TopicsControllerGetTopicSubscriberResponse> {
    return unwrapAsync(topicsSubscribersRetrieve(
      this,
      topicKey,
      externalSubscriberId,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Subscribers removal
   *
   * @remarks
   * Remove subscribers from a topic
   */
  async remove(
    removeSubscribersRequestDto: RemoveSubscribersRequestDto,
    topicKey: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<TopicsControllerRemoveSubscribersResponse | undefined> {
    return unwrapAsync(topicsSubscribersRemove(
      this,
      removeSubscribersRequestDto,
      topicKey,
      idempotencyKey,
      options,
    ));
  }
}
