/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscribersMessagesMarkAll } from "../funcs/subscribersMessagesMarkAll.js";
import { subscribersMessagesMarkAllAs } from "../funcs/subscribersMessagesMarkAllAs.js";
import { subscribersMessagesUpdateAsSeen } from "../funcs/subscribersMessagesUpdateAsSeen.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { MarkAllMessageAsRequestDto } from "../models/components/markallmessageasrequestdto.js";
import { MessageMarkAsRequestDto } from "../models/components/messagemarkasrequestdto.js";
import {
  SubscribersV1ControllerMarkActionAsSeenRequest,
  SubscribersV1ControllerMarkActionAsSeenResponse,
} from "../models/operations/subscribersv1controllermarkactionasseen.js";
import { SubscribersV1ControllerMarkAllUnreadAsReadResponse } from "../models/operations/subscribersv1controllermarkallunreadasread.js";
import { SubscribersV1ControllerMarkMessagesAsResponse } from "../models/operations/subscribersv1controllermarkmessagesas.js";
import { unwrapAsync } from "../types/fp.js";

export class NovuMessages extends ClientSDK {
  /**
   * Mark message action as seen
   */
  async updateAsSeen(
    request: SubscribersV1ControllerMarkActionAsSeenRequest,
    options?: RequestOptions,
  ): Promise<SubscribersV1ControllerMarkActionAsSeenResponse> {
    return unwrapAsync(subscribersMessagesUpdateAsSeen(
      this,
      request,
      options,
    ));
  }

  /**
   * Marks all the subscriber messages as read, unread, seen or unseen. Optionally you can pass feed id (or array) to mark messages of a particular feed.
   */
  async markAll(
    markAllMessageAsRequestDto: MarkAllMessageAsRequestDto,
    subscriberId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<SubscribersV1ControllerMarkAllUnreadAsReadResponse> {
    return unwrapAsync(subscribersMessagesMarkAll(
      this,
      markAllMessageAsRequestDto,
      subscriberId,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Mark a subscriber messages as seen, read, unseen or unread
   */
  async markAllAs(
    messageMarkAsRequestDto: MessageMarkAsRequestDto,
    subscriberId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<SubscribersV1ControllerMarkMessagesAsResponse> {
    return unwrapAsync(subscribersMessagesMarkAllAs(
      this,
      messageMarkAsRequestDto,
      subscriberId,
      idempotencyKey,
      options,
    ));
  }
}
