/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscribersPreferencesList } from "../funcs/subscribersPreferencesList.js";
import { subscribersPreferencesUpdate } from "../funcs/subscribersPreferencesUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { PatchSubscriberPreferencesDto } from "../models/components/patchsubscriberpreferencesdto.js";
import { SubscribersControllerGetSubscriberPreferencesResponse } from "../models/operations/subscriberscontrollergetsubscriberpreferences.js";
import { SubscribersControllerUpdateSubscriberPreferencesResponse } from "../models/operations/subscriberscontrollerupdatesubscriberpreferences.js";
import { unwrapAsync } from "../types/fp.js";

export class Preferences extends ClientSDK {
  /**
   * Get subscriber preferences
   *
   * @remarks
   * Get subscriber global and workflow specific preferences
   */
  async list(
    subscriberId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<SubscribersControllerGetSubscriberPreferencesResponse> {
    return unwrapAsync(subscribersPreferencesList(
      this,
      subscriberId,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Update subscriber global or workflow specific preferences
   *
   * @remarks
   * Update subscriber global or workflow specific preferences
   */
  async update(
    patchSubscriberPreferencesDto: PatchSubscriberPreferencesDto,
    subscriberId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<SubscribersControllerUpdateSubscriberPreferencesResponse> {
    return unwrapAsync(subscribersPreferencesUpdate(
      this,
      patchSubscriberPreferencesDto,
      subscriberId,
      idempotencyKey,
      options,
    ));
  }
}
