/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscribersPropertiesUpdateOnlineFlag } from "../funcs/subscribersPropertiesUpdateOnlineFlag.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { UpdateSubscriberOnlineFlagRequestDto } from "../models/components/updatesubscriberonlineflagrequestdto.js";
import { SubscribersV1ControllerUpdateSubscriberOnlineFlagResponse } from "../models/operations/subscribersv1controllerupdatesubscriberonlineflag.js";
import { unwrapAsync } from "../types/fp.js";

export class Properties extends ClientSDK {
  /**
   * Update subscriber online status
   *
   * @remarks
   * Used to update the subscriber isOnline flag.
   */
  async updateOnlineFlag(
    updateSubscriberOnlineFlagRequestDto: UpdateSubscriberOnlineFlagRequestDto,
    subscriberId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<SubscribersV1ControllerUpdateSubscriberOnlineFlagResponse> {
    return unwrapAsync(subscribersPropertiesUpdateOnlineFlag(
      this,
      updateSubscriberOnlineFlagRequestDto,
      subscriberId,
      idempotencyKey,
      options,
    ));
  }
}
