/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { notificationsStatsGraph } from "../funcs/notificationsStatsGraph.js";
import { notificationsStatsRetrieve } from "../funcs/notificationsStatsRetrieve.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { NotificationsControllerGetActivityGraphStatsResponse } from "../models/operations/notificationscontrollergetactivitygraphstats.js";
import { NotificationsControllerGetActivityStatsResponse } from "../models/operations/notificationscontrollergetactivitystats.js";
import { unwrapAsync } from "../types/fp.js";

export class Stats extends ClientSDK {
  /**
   * Get notification graph statistics
   */
  async graph(
    days?: number | undefined,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<NotificationsControllerGetActivityGraphStatsResponse> {
    return unwrapAsync(notificationsStatsGraph(
      this,
      days,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Get notification statistics
   */
  async retrieve(
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<NotificationsControllerGetActivityStatsResponse> {
    return unwrapAsync(notificationsStatsRetrieve(
      this,
      idempotencyKey,
      options,
    ));
  }
}
