/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { topicsCreate } from "../funcs/topicsCreate.js";
import { topicsDelete } from "../funcs/topicsDelete.js";
import { topicsList } from "../funcs/topicsList.js";
import { topicsRename } from "../funcs/topicsRename.js";
import { topicsRetrieve } from "../funcs/topicsRetrieve.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { CreateTopicRequestDto } from "../models/components/createtopicrequestdto.js";
import { RenameTopicRequestDto } from "../models/components/renametopicrequestdto.js";
import { TopicsControllerCreateTopicResponse } from "../models/operations/topicscontrollercreatetopic.js";
import { TopicsControllerDeleteTopicResponse } from "../models/operations/topicscontrollerdeletetopic.js";
import { TopicsControllerGetTopicResponse } from "../models/operations/topicscontrollergettopic.js";
import {
  TopicsControllerListTopicsRequest,
  TopicsControllerListTopicsResponse,
} from "../models/operations/topicscontrollerlisttopics.js";
import { TopicsControllerRenameTopicResponse } from "../models/operations/topicscontrollerrenametopic.js";
import { unwrapAsync } from "../types/fp.js";
import { NovuSubscribers } from "./novusubscribers.js";

export class Topics extends ClientSDK {
  private _subscribers?: NovuSubscribers;
  get subscribers(): NovuSubscribers {
    return (this._subscribers ??= new NovuSubscribers(this._options));
  }

  /**
   * Topic creation
   *
   * @remarks
   * Create a topic
   */
  async create(
    createTopicRequestDto: CreateTopicRequestDto,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<TopicsControllerCreateTopicResponse> {
    return unwrapAsync(topicsCreate(
      this,
      createTopicRequestDto,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Get topic list filtered
   *
   * @remarks
   * Returns a list of topics that can be paginated using the `page` query parameter and filtered by the topic key with the `key` query parameter
   */
  async list(
    request: TopicsControllerListTopicsRequest,
    options?: RequestOptions,
  ): Promise<TopicsControllerListTopicsResponse> {
    return unwrapAsync(topicsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete topic
   *
   * @remarks
   * Delete a topic by its topic key if it has no subscribers
   */
  async delete(
    topicKey: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<TopicsControllerDeleteTopicResponse | undefined> {
    return unwrapAsync(topicsDelete(
      this,
      topicKey,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Get topic
   *
   * @remarks
   * Get a topic by its topic key
   */
  async retrieve(
    topicKey: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<TopicsControllerGetTopicResponse> {
    return unwrapAsync(topicsRetrieve(
      this,
      topicKey,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Rename a topic
   *
   * @remarks
   * Rename a topic by providing a new name
   */
  async rename(
    renameTopicRequestDto: RenameTopicRequestDto,
    topicKey: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<TopicsControllerRenameTopicResponse> {
    return unwrapAsync(topicsRename(
      this,
      renameTopicRequestDto,
      topicKey,
      idempotencyKey,
      options,
    ));
  }
}
