/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workflowsCreate } from "../funcs/workflowsCreate.js";
import { workflowsDelete } from "../funcs/workflowsDelete.js";
import { workflowsGetStepData } from "../funcs/workflowsGetStepData.js";
import { workflowsGetWorkflowTestData } from "../funcs/workflowsGetWorkflowTestData.js";
import { workflowsPatch } from "../funcs/workflowsPatch.js";
import { workflowsRetrieve } from "../funcs/workflowsRetrieve.js";
import { workflowsUpdate } from "../funcs/workflowsUpdate.js";
import { workflowsWorkflowControllerGeneratePreview } from "../funcs/workflowsWorkflowControllerGeneratePreview.js";
import { workflowsWorkflowControllerPatchWorkflowStepData } from "../funcs/workflowsWorkflowControllerPatchWorkflowStepData.js";
import { workflowsWorkflowControllerSearchWorkflows } from "../funcs/workflowsWorkflowControllerSearchWorkflows.js";
import { workflowsWorkflowControllerSync } from "../funcs/workflowsWorkflowControllerSync.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Workflows extends ClientSDK {
  /**
   * Topic creation
   *
   * @remarks
   * Create a topic
   */
  async create(
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.WorkflowControllerCreateResponse> {
    return unwrapAsync(workflowsCreate(
      this,
      idempotencyKey,
      options,
    ));
  }

  async workflowControllerSearchWorkflows(
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.WorkflowControllerSearchWorkflowsResponse> {
    return unwrapAsync(workflowsWorkflowControllerSearchWorkflows(
      this,
      idempotencyKey,
      options,
    ));
  }

  async workflowControllerSync(
    workflowId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.WorkflowControllerSyncResponse> {
    return unwrapAsync(workflowsWorkflowControllerSync(
      this,
      workflowId,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Update subscriber global or workflow specific preferences
   *
   * @remarks
   * Update subscriber global or workflow specific preferences
   */
  async update(
    workflowId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.WorkflowControllerUpdateResponse> {
    return unwrapAsync(workflowsUpdate(
      this,
      workflowId,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Get topic
   *
   * @remarks
   * Get a topic by its topic key
   */
  async retrieve(
    workflowId: string,
    environmentId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.WorkflowControllerGetWorkflowResponse> {
    return unwrapAsync(workflowsRetrieve(
      this,
      workflowId,
      environmentId,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Delete topic
   *
   * @remarks
   * Delete a topic by its topic key if it has no subscribers
   */
  async delete(
    workflowId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.WorkflowControllerRemoveWorkflowResponse | undefined> {
    return unwrapAsync(workflowsDelete(
      this,
      workflowId,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Patch subscriber
   *
   * @remarks
   * Patch subscriber by your internal id used to identify the subscriber
   */
  async patch(
    patchWorkflowDto: components.PatchWorkflowDto,
    workflowId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.WorkflowControllerPatchWorkflowResponse> {
    return unwrapAsync(workflowsPatch(
      this,
      patchWorkflowDto,
      workflowId,
      idempotencyKey,
      options,
    ));
  }

  async workflowControllerGeneratePreview(
    workflowId: string,
    stepId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.WorkflowControllerGeneratePreviewResponse> {
    return unwrapAsync(workflowsWorkflowControllerGeneratePreview(
      this,
      workflowId,
      stepId,
      idempotencyKey,
      options,
    ));
  }

  async getStepData(
    workflowId: string,
    stepId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.WorkflowControllerGetWorkflowStepDataResponse> {
    return unwrapAsync(workflowsGetStepData(
      this,
      workflowId,
      stepId,
      idempotencyKey,
      options,
    ));
  }

  async workflowControllerPatchWorkflowStepData(
    workflowId: string,
    stepId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.WorkflowControllerPatchWorkflowStepDataResponse> {
    return unwrapAsync(workflowsWorkflowControllerPatchWorkflowStepData(
      this,
      workflowId,
      stepId,
      idempotencyKey,
      options,
    ));
  }

  async getWorkflowTestData(
    workflowId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.WorkflowControllerGetWorkflowTestDataResponse> {
    return unwrapAsync(workflowsGetWorkflowTestData(
      this,
      workflowId,
      idempotencyKey,
      options,
    ));
  }
}
