/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workflowsCreate } from "../funcs/workflowsCreate.js";
import { workflowsDelete } from "../funcs/workflowsDelete.js";
import { workflowsGetStepData } from "../funcs/workflowsGetStepData.js";
import { workflowsGetWorkflowTestData } from "../funcs/workflowsGetWorkflowTestData.js";
import { workflowsRetrieve } from "../funcs/workflowsRetrieve.js";
import { workflowsUpdate } from "../funcs/workflowsUpdate.js";
import { workflowsWorkflowControllerGeneratePreview } from "../funcs/workflowsWorkflowControllerGeneratePreview.js";
import { workflowsWorkflowControllerPatchWorkflow } from "../funcs/workflowsWorkflowControllerPatchWorkflow.js";
import { workflowsWorkflowControllerPatchWorkflowStepData } from "../funcs/workflowsWorkflowControllerPatchWorkflowStepData.js";
import { workflowsWorkflowControllerSearchWorkflows } from "../funcs/workflowsWorkflowControllerSearchWorkflows.js";
import { workflowsWorkflowControllerSync } from "../funcs/workflowsWorkflowControllerSync.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { WorkflowControllerCreateResponse } from "../models/operations/workflowcontrollercreate.js";
import { WorkflowControllerGeneratePreviewResponse } from "../models/operations/workflowcontrollergeneratepreview.js";
import { WorkflowControllerGetWorkflowResponse } from "../models/operations/workflowcontrollergetworkflow.js";
import { WorkflowControllerGetWorkflowStepDataResponse } from "../models/operations/workflowcontrollergetworkflowstepdata.js";
import { WorkflowControllerGetWorkflowTestDataResponse } from "../models/operations/workflowcontrollergetworkflowtestdata.js";
import { WorkflowControllerPatchWorkflowResponse } from "../models/operations/workflowcontrollerpatchworkflow.js";
import { WorkflowControllerPatchWorkflowStepDataResponse } from "../models/operations/workflowcontrollerpatchworkflowstepdata.js";
import { WorkflowControllerRemoveWorkflowResponse } from "../models/operations/workflowcontrollerremoveworkflow.js";
import { WorkflowControllerSearchWorkflowsResponse } from "../models/operations/workflowcontrollersearchworkflows.js";
import { WorkflowControllerSyncResponse } from "../models/operations/workflowcontrollersync.js";
import { WorkflowControllerUpdateResponse } from "../models/operations/workflowcontrollerupdate.js";
import { unwrapAsync } from "../types/fp.js";

export class Workflows extends ClientSDK {
  /**
   * Create subscriber
   *
   * @remarks
   * Create subscriber with the given data
   */
  async create(
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<WorkflowControllerCreateResponse> {
    return unwrapAsync(workflowsCreate(
      this,
      idempotencyKey,
      options,
    ));
  }

  async workflowControllerSearchWorkflows(
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<WorkflowControllerSearchWorkflowsResponse> {
    return unwrapAsync(workflowsWorkflowControllerSearchWorkflows(
      this,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Update subscriber credentials
   *
   * @remarks
   * Subscriber credentials associated to the delivery methods such as slack and push tokens.
   */
  async update(
    workflowId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<WorkflowControllerUpdateResponse> {
    return unwrapAsync(workflowsUpdate(
      this,
      workflowId,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Get subscriber
   *
   * @remarks
   * Get subscriber by your internal id used to identify the subscriber
   */
  async retrieve(
    workflowId: string,
    environmentId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<WorkflowControllerGetWorkflowResponse> {
    return unwrapAsync(workflowsRetrieve(
      this,
      workflowId,
      environmentId,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Delete subscriber
   *
   * @remarks
   * Deletes a subscriber entity from the Novu platform
   */
  async delete(
    workflowId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<WorkflowControllerRemoveWorkflowResponse | undefined> {
    return unwrapAsync(workflowsDelete(
      this,
      workflowId,
      idempotencyKey,
      options,
    ));
  }

  async workflowControllerPatchWorkflow(
    workflowId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<WorkflowControllerPatchWorkflowResponse> {
    return unwrapAsync(workflowsWorkflowControllerPatchWorkflow(
      this,
      workflowId,
      idempotencyKey,
      options,
    ));
  }

  async workflowControllerGeneratePreview(
    workflowId: string,
    stepId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<WorkflowControllerGeneratePreviewResponse> {
    return unwrapAsync(workflowsWorkflowControllerGeneratePreview(
      this,
      workflowId,
      stepId,
      idempotencyKey,
      options,
    ));
  }

  async getStepData(
    workflowId: string,
    stepId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<WorkflowControllerGetWorkflowStepDataResponse> {
    return unwrapAsync(workflowsGetStepData(
      this,
      workflowId,
      stepId,
      idempotencyKey,
      options,
    ));
  }

  async workflowControllerPatchWorkflowStepData(
    workflowId: string,
    stepId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<WorkflowControllerPatchWorkflowStepDataResponse> {
    return unwrapAsync(workflowsWorkflowControllerPatchWorkflowStepData(
      this,
      workflowId,
      stepId,
      idempotencyKey,
      options,
    ));
  }

  async workflowControllerSync(
    workflowId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<WorkflowControllerSyncResponse> {
    return unwrapAsync(workflowsWorkflowControllerSync(
      this,
      workflowId,
      idempotencyKey,
      options,
    ));
  }

  async getWorkflowTestData(
    workflowId: string,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<WorkflowControllerGetWorkflowTestDataResponse> {
    return unwrapAsync(workflowsGetWorkflowTestData(
      this,
      workflowId,
      idempotencyKey,
      options,
    ));
  }
}
