import { SDKOptions } from '@novu/api/lib/config';
import { HTTPClient, HTTPClientOptions } from '@novu/api/lib/http';
// This is how we import the speakeasy autogenerated Novu SDK that is CJS in a the Dashboard ESM project with Vite
// Read more at https://github.com/vitejs/vite/issues/5668#issuecomment-968117934
/** DO NOT CHANGE THIS CODE START */
import * as NovuAPI from '@novu/api';
import { IEnvironment } from '@novu/shared';
import { getToken } from '@/utils/auth.ts';
import { API_HOSTNAME } from '@/config';

const { Novu } = NovuAPI;

/** DO NOT CHANGE THIS CODE END */
export async function initNovuSdk(env: IEnvironment) {
  const options: SDKOptions = {
    security: { bearerAuth: await getToken() },
    serverURL: API_HOSTNAME ?? 'https://api.novu.co',
    httpClient: new CustomHeaderHTTPClient({
      ['Novu-Environment-Id']: env._id,
    }),
    // debugLogger: console,
  };

  return new Novu(options);
}

export class CustomHeaderHTTPClient extends HTTPClient {
  private defaultHeaders: HeadersInit;

  constructor(defaultHeaders: HeadersInit = {}, options: HTTPClientOptions = {}) {
    super(options);
    this.defaultHeaders = defaultHeaders;
  }

  async request(request: Request): Promise<Response> {
    // Create a new request with merged headers
    const mergedHeaders = new Headers(this.defaultHeaders);

    /*
     * Merge existing request headers with default headers
     * Existing request headers take precedence
     */
    request.headers.forEach((value, key) => {
      mergedHeaders.set(key, value);
    });

    // Create a new request with merged headers
    const modifiedRequest = new Request(request, {
      headers: mergedHeaders,
    });

    // Call the parent class's request method with the modified request
    return super.request(modifiedRequest);
  }
}
