/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type EnvironmentsControllerGenerateSessionRequest = {
  subscriberId: string;
  /**
   * A header for idempotency purposes
   */
  idempotencyKey?: string | undefined;
};

export type EnvironmentsControllerGenerateSessionResponse = {
  headers: { [k: string]: Array<string> };
  result: components.SessionGeneratedResponseDto;
};

/** @internal */
export const EnvironmentsControllerGenerateSessionRequest$inboundSchema:
  z.ZodType<
    EnvironmentsControllerGenerateSessionRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    subscriberId: z.string(),
    "idempotency-key": z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "idempotency-key": "idempotencyKey",
    });
  });

/** @internal */
export type EnvironmentsControllerGenerateSessionRequest$Outbound = {
  subscriberId: string;
  "idempotency-key"?: string | undefined;
};

/** @internal */
export const EnvironmentsControllerGenerateSessionRequest$outboundSchema:
  z.ZodType<
    EnvironmentsControllerGenerateSessionRequest$Outbound,
    z.ZodTypeDef,
    EnvironmentsControllerGenerateSessionRequest
  > = z.object({
    subscriberId: z.string(),
    idempotencyKey: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      idempotencyKey: "idempotency-key",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EnvironmentsControllerGenerateSessionRequest$ {
  /** @deprecated use `EnvironmentsControllerGenerateSessionRequest$inboundSchema` instead. */
  export const inboundSchema =
    EnvironmentsControllerGenerateSessionRequest$inboundSchema;
  /** @deprecated use `EnvironmentsControllerGenerateSessionRequest$outboundSchema` instead. */
  export const outboundSchema =
    EnvironmentsControllerGenerateSessionRequest$outboundSchema;
  /** @deprecated use `EnvironmentsControllerGenerateSessionRequest$Outbound` instead. */
  export type Outbound = EnvironmentsControllerGenerateSessionRequest$Outbound;
}

export function environmentsControllerGenerateSessionRequestToJSON(
  environmentsControllerGenerateSessionRequest:
    EnvironmentsControllerGenerateSessionRequest,
): string {
  return JSON.stringify(
    EnvironmentsControllerGenerateSessionRequest$outboundSchema.parse(
      environmentsControllerGenerateSessionRequest,
    ),
  );
}

export function environmentsControllerGenerateSessionRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  EnvironmentsControllerGenerateSessionRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      EnvironmentsControllerGenerateSessionRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'EnvironmentsControllerGenerateSessionRequest' from JSON`,
  );
}

/** @internal */
export const EnvironmentsControllerGenerateSessionResponse$inboundSchema:
  z.ZodType<
    EnvironmentsControllerGenerateSessionResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())),
    Result: components.SessionGeneratedResponseDto$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });

/** @internal */
export type EnvironmentsControllerGenerateSessionResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.SessionGeneratedResponseDto$Outbound;
};

/** @internal */
export const EnvironmentsControllerGenerateSessionResponse$outboundSchema:
  z.ZodType<
    EnvironmentsControllerGenerateSessionResponse$Outbound,
    z.ZodTypeDef,
    EnvironmentsControllerGenerateSessionResponse
  > = z.object({
    headers: z.record(z.array(z.string())),
    result: components.SessionGeneratedResponseDto$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      headers: "Headers",
      result: "Result",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EnvironmentsControllerGenerateSessionResponse$ {
  /** @deprecated use `EnvironmentsControllerGenerateSessionResponse$inboundSchema` instead. */
  export const inboundSchema =
    EnvironmentsControllerGenerateSessionResponse$inboundSchema;
  /** @deprecated use `EnvironmentsControllerGenerateSessionResponse$outboundSchema` instead. */
  export const outboundSchema =
    EnvironmentsControllerGenerateSessionResponse$outboundSchema;
  /** @deprecated use `EnvironmentsControllerGenerateSessionResponse$Outbound` instead. */
  export type Outbound = EnvironmentsControllerGenerateSessionResponse$Outbound;
}

export function environmentsControllerGenerateSessionResponseToJSON(
  environmentsControllerGenerateSessionResponse:
    EnvironmentsControllerGenerateSessionResponse,
): string {
  return JSON.stringify(
    EnvironmentsControllerGenerateSessionResponse$outboundSchema.parse(
      environmentsControllerGenerateSessionResponse,
    ),
  );
}

export function environmentsControllerGenerateSessionResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  EnvironmentsControllerGenerateSessionResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      EnvironmentsControllerGenerateSessionResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'EnvironmentsControllerGenerateSessionResponse' from JSON`,
  );
}
