/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Action button type: primary or secondary
 */
export const Type = {
  Primary: "primary",
  Secondary: "secondary",
} as const;
/**
 * Action button type: primary or secondary
 */
export type Type = ClosedEnum<typeof Type>;

export type SubscribersV1ControllerMarkActionAsSeenRequest = {
  messageId: string;
  /**
   * Action button type: primary or secondary
   */
  type: Type;
  subscriberId: string;
  /**
   * A header for idempotency purposes
   */
  idempotencyKey?: string | undefined;
  markMessageActionAsSeenDto: components.MarkMessageActionAsSeenDto;
};

export type SubscribersV1ControllerMarkActionAsSeenResponse = {
  headers: { [k: string]: Array<string> };
  result: components.MessageResponseDto;
};

/** @internal */
export const Type$outboundSchema: z.ZodNativeEnum<typeof Type> = z.nativeEnum(
  Type,
);

/** @internal */
export type SubscribersV1ControllerMarkActionAsSeenRequest$Outbound = {
  messageId: string;
  type: string;
  subscriberId: string;
  "idempotency-key"?: string | undefined;
  MarkMessageActionAsSeenDto: components.MarkMessageActionAsSeenDto$Outbound;
};

/** @internal */
export const SubscribersV1ControllerMarkActionAsSeenRequest$outboundSchema:
  z.ZodType<
    SubscribersV1ControllerMarkActionAsSeenRequest$Outbound,
    z.ZodTypeDef,
    SubscribersV1ControllerMarkActionAsSeenRequest
  > = z.object({
    messageId: z.string(),
    type: Type$outboundSchema,
    subscriberId: z.string(),
    idempotencyKey: z.string().optional(),
    markMessageActionAsSeenDto:
      components.MarkMessageActionAsSeenDto$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      idempotencyKey: "idempotency-key",
      markMessageActionAsSeenDto: "MarkMessageActionAsSeenDto",
    });
  });

export function subscribersV1ControllerMarkActionAsSeenRequestToJSON(
  subscribersV1ControllerMarkActionAsSeenRequest:
    SubscribersV1ControllerMarkActionAsSeenRequest,
): string {
  return JSON.stringify(
    SubscribersV1ControllerMarkActionAsSeenRequest$outboundSchema.parse(
      subscribersV1ControllerMarkActionAsSeenRequest,
    ),
  );
}

/** @internal */
export const SubscribersV1ControllerMarkActionAsSeenResponse$inboundSchema:
  z.ZodType<
    SubscribersV1ControllerMarkActionAsSeenResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())).default({}),
    Result: components.MessageResponseDto$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });

export function subscribersV1ControllerMarkActionAsSeenResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  SubscribersV1ControllerMarkActionAsSeenResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SubscribersV1ControllerMarkActionAsSeenResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SubscribersV1ControllerMarkActionAsSeenResponse' from JSON`,
  );
}
