/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TopicsControllerUpdateTopicSubscriptionRequest = {
  /**
   * The key identifier of the topic
   */
  topicKey: string;
  /**
   * The unique identifier of the subscription
   */
  subscriptionId: string;
  /**
   * A header for idempotency purposes
   */
  idempotencyKey?: string | undefined;
  updateTopicSubscriptionRequestDto:
    components.UpdateTopicSubscriptionRequestDto;
};

export type TopicsControllerUpdateTopicSubscriptionResponse = {
  headers: { [k: string]: Array<string> };
  result: components.SubscriptionDto;
};

/** @internal */
export const TopicsControllerUpdateTopicSubscriptionRequest$inboundSchema:
  z.ZodType<
    TopicsControllerUpdateTopicSubscriptionRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    topicKey: z.string(),
    subscriptionId: z.string(),
    "idempotency-key": z.string().optional(),
    UpdateTopicSubscriptionRequestDto:
      components.UpdateTopicSubscriptionRequestDto$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "idempotency-key": "idempotencyKey",
      "UpdateTopicSubscriptionRequestDto": "updateTopicSubscriptionRequestDto",
    });
  });

/** @internal */
export type TopicsControllerUpdateTopicSubscriptionRequest$Outbound = {
  topicKey: string;
  subscriptionId: string;
  "idempotency-key"?: string | undefined;
  UpdateTopicSubscriptionRequestDto:
    components.UpdateTopicSubscriptionRequestDto$Outbound;
};

/** @internal */
export const TopicsControllerUpdateTopicSubscriptionRequest$outboundSchema:
  z.ZodType<
    TopicsControllerUpdateTopicSubscriptionRequest$Outbound,
    z.ZodTypeDef,
    TopicsControllerUpdateTopicSubscriptionRequest
  > = z.object({
    topicKey: z.string(),
    subscriptionId: z.string(),
    idempotencyKey: z.string().optional(),
    updateTopicSubscriptionRequestDto:
      components.UpdateTopicSubscriptionRequestDto$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      idempotencyKey: "idempotency-key",
      updateTopicSubscriptionRequestDto: "UpdateTopicSubscriptionRequestDto",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TopicsControllerUpdateTopicSubscriptionRequest$ {
  /** @deprecated use `TopicsControllerUpdateTopicSubscriptionRequest$inboundSchema` instead. */
  export const inboundSchema =
    TopicsControllerUpdateTopicSubscriptionRequest$inboundSchema;
  /** @deprecated use `TopicsControllerUpdateTopicSubscriptionRequest$outboundSchema` instead. */
  export const outboundSchema =
    TopicsControllerUpdateTopicSubscriptionRequest$outboundSchema;
  /** @deprecated use `TopicsControllerUpdateTopicSubscriptionRequest$Outbound` instead. */
  export type Outbound =
    TopicsControllerUpdateTopicSubscriptionRequest$Outbound;
}

export function topicsControllerUpdateTopicSubscriptionRequestToJSON(
  topicsControllerUpdateTopicSubscriptionRequest:
    TopicsControllerUpdateTopicSubscriptionRequest,
): string {
  return JSON.stringify(
    TopicsControllerUpdateTopicSubscriptionRequest$outboundSchema.parse(
      topicsControllerUpdateTopicSubscriptionRequest,
    ),
  );
}

export function topicsControllerUpdateTopicSubscriptionRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  TopicsControllerUpdateTopicSubscriptionRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TopicsControllerUpdateTopicSubscriptionRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TopicsControllerUpdateTopicSubscriptionRequest' from JSON`,
  );
}

/** @internal */
export const TopicsControllerUpdateTopicSubscriptionResponse$inboundSchema:
  z.ZodType<
    TopicsControllerUpdateTopicSubscriptionResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())).default({}),
    Result: components.SubscriptionDto$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });

/** @internal */
export type TopicsControllerUpdateTopicSubscriptionResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.SubscriptionDto$Outbound;
};

/** @internal */
export const TopicsControllerUpdateTopicSubscriptionResponse$outboundSchema:
  z.ZodType<
    TopicsControllerUpdateTopicSubscriptionResponse$Outbound,
    z.ZodTypeDef,
    TopicsControllerUpdateTopicSubscriptionResponse
  > = z.object({
    headers: z.record(z.array(z.string())),
    result: components.SubscriptionDto$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      headers: "Headers",
      result: "Result",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TopicsControllerUpdateTopicSubscriptionResponse$ {
  /** @deprecated use `TopicsControllerUpdateTopicSubscriptionResponse$inboundSchema` instead. */
  export const inboundSchema =
    TopicsControllerUpdateTopicSubscriptionResponse$inboundSchema;
  /** @deprecated use `TopicsControllerUpdateTopicSubscriptionResponse$outboundSchema` instead. */
  export const outboundSchema =
    TopicsControllerUpdateTopicSubscriptionResponse$outboundSchema;
  /** @deprecated use `TopicsControllerUpdateTopicSubscriptionResponse$Outbound` instead. */
  export type Outbound =
    TopicsControllerUpdateTopicSubscriptionResponse$Outbound;
}

export function topicsControllerUpdateTopicSubscriptionResponseToJSON(
  topicsControllerUpdateTopicSubscriptionResponse:
    TopicsControllerUpdateTopicSubscriptionResponse,
): string {
  return JSON.stringify(
    TopicsControllerUpdateTopicSubscriptionResponse$outboundSchema.parse(
      topicsControllerUpdateTopicSubscriptionResponse,
    ),
  );
}

export function topicsControllerUpdateTopicSubscriptionResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  TopicsControllerUpdateTopicSubscriptionResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TopicsControllerUpdateTopicSubscriptionResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TopicsControllerUpdateTopicSubscriptionResponse' from JSON`,
  );
}
