/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { NovuCore } from "../core.js";
import { encodeFormQuery, encodeSimple } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { ErrorDto, ErrorDto$inboundSchema } from "../models/errors/errordto.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKError } from "../models/errors/sdkerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import {
  ValidationErrorDto,
  ValidationErrorDto$inboundSchema,
} from "../models/errors/validationerrordto.js";
import {
  SubscribersV1ControllerChatAccessOauthRequest,
  SubscribersV1ControllerChatAccessOauthRequest$outboundSchema,
  SubscribersV1ControllerChatAccessOauthResponse,
  SubscribersV1ControllerChatAccessOauthResponse$inboundSchema,
} from "../models/operations/subscribersv1controllerchataccessoauth.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Handle chat oauth
 */
export function subscribersAuthenticationChatAccessOauth(
  client: NovuCore,
  request: SubscribersV1ControllerChatAccessOauthRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    SubscribersV1ControllerChatAccessOauthResponse | undefined,
    | ErrorDto
    | ErrorDto
    | ValidationErrorDto
    | ErrorDto
    | SDKError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client,
    request,
    options,
  ));
}

async function $do(
  client: NovuCore,
  request: SubscribersV1ControllerChatAccessOauthRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      SubscribersV1ControllerChatAccessOauthResponse | undefined,
      | ErrorDto
      | ErrorDto
      | ValidationErrorDto
      | ErrorDto
      | SDKError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) =>
      SubscribersV1ControllerChatAccessOauthRequest$outboundSchema.parse(value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = null;

  const pathParams = {
    providerId: encodeSimple("providerId", payload.providerId, {
      explode: false,
      charEncoding: "percent",
    }),
    subscriberId: encodeSimple("subscriberId", payload.subscriberId, {
      explode: false,
      charEncoding: "percent",
    }),
  };

  const path = pathToFunc(
    "/v1/subscribers/{subscriberId}/credentials/{providerId}/oauth",
  )(pathParams);

  const query = encodeFormQuery({
    "environmentId": payload.environmentId,
    "hmacHash": payload.hmacHash,
    "integrationIdentifier": payload.integrationIdentifier,
  });

  const headers = new Headers(compactMap({
    Accept: "application/json",
    "idempotency-key": encodeSimple(
      "idempotency-key",
      payload["idempotency-key"],
      { explode: false, charEncoding: "none" },
    ),
  }));

  const securityInput = await extractSecurity(client._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "SubscribersV1Controller_chatAccessOauth",
    oAuth2Scopes: [],

    resolvedSecurity: requestSecurity,

    securitySource: client._options.security,
    retryConfig: options?.retries
      || client._options.retryConfig
      || {
        strategy: "backoff",
        backoff: {
          initialInterval: 1000,
          maxInterval: 30000,
          exponent: 1.5,
          maxElapsedTime: 3600000,
        },
        retryConnectionErrors: true,
      }
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["408", "409", "429", "5XX"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    query: query,
    body: body,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: [
      "400",
      "401",
      "403",
      "404",
      "405",
      "409",
      "413",
      "414",
      "415",
      "422",
      "429",
      "4XX",
      "500",
      "503",
      "5XX",
    ],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    SubscribersV1ControllerChatAccessOauthResponse | undefined,
    | ErrorDto
    | ErrorDto
    | ValidationErrorDto
    | ErrorDto
    | SDKError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.nil(
      200,
      SubscribersV1ControllerChatAccessOauthResponse$inboundSchema.optional(),
    ),
    M.jsonErr(414, ErrorDto$inboundSchema),
    M.jsonErr(
      [400, 401, 403, 404, 405, 409, 413, 415],
      ErrorDto$inboundSchema,
      { hdrs: true },
    ),
    M.jsonErr(422, ValidationErrorDto$inboundSchema, { hdrs: true }),
    M.fail(429),
    M.jsonErr(500, ErrorDto$inboundSchema, { hdrs: true }),
    M.fail(503),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
